{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<html xmlns="http://www.w3.org/1999/html">
<head>
<title>{$module_result.content_info.persistent_variable.mailing_subject|wash}</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="pragma" content="no-cache">
<meta http-equiv="cache-control" content="no-cache">
<meta http-equiv="expires" content="0">
</head>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<!-- Save for Web Slices (EzNova.psd) -->
<table id="Tableau_01" width="701" height="1722" border="0" cellpadding="0" cellspacing="0" style="font-family:Verdana, Geneva, sans-serif; font-size:11px;" align="center">
	<tr>
		<td width="700" height="40" colspan="5" align="center" valign="middle">
        <div style="color:#434343;"><a href="#WEBVIEW_LINK#" target="_blank" style="color:#e46809;">{"If you have trouble viewing this email, read the online version."|i18n( 'extension/ezmailing/text' )}</a>&nbsp; | &nbsp;<a href={"mailing/unregister/"|ezurl} target="_blank" style="color:#e46809;">{"Unsubscribe from the mailing list."|i18n( 'extension/ezmailing/text' )}</a></div>
			</td>
		<td width="1" height="40">
			<img src={"spacer-top.jpg"|ezimage} width="1" height="40" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="16" height="183" rowspan="8">
			<img src={"mailingtest/EzNova_02.jpg"|ezimage} width="16" height="183" alt="" style="display:block; border:0;"></td>
		<td width="662" height="15" colspan="3">
			<img src={"mailingtest/EzNova_03.jpg"|ezimage} width="662" height="15" alt="" style="display:block; border:0;"></td>
		<td width="22" height="183" rowspan="8">
			<img src={"mailingtest/EzNova_04.jpg"|ezimage} width="22" height="183" alt="" style="display:block; border:0;"></td>
		<td width="1" height="15">
			<img src={"spacer-top.jpg"|ezimage} width="1" height="15" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="662" height="22" colspan="3" bgcolor="#f6f6f6">
			<div style="font-size:12px; color:#e46809;">{$module_result.content_info.persistent_variable.mailing_date|wash}</div></td>
		<td width="1" height="22">
			<img src={"spacer-top.jpg"|ezimage} width="1" height="22" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="662" height="5" colspan="3">
			<img src={"mailingtest/EzNova_06.jpg"|ezimage} width="662" height="5" alt="" style="display:block; border:0;"></td>
		<td width="1" height="5">
			<img src={"spacer-top.jpg"|ezimage} width="1" height="5" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="521" height="64" colspan="2" rowspan="2" bgcolor="#f6f6f6" valign="top">
			<div style="font-size:25px; color:#434343;">{$module_result.content_info.persistent_variable.mailing_subject}</div></td>
		<td width="141" height="43">
			<img src={"mailingtest/EzNova_08.jpg"|ezimage} width="141" height="43" alt="" style="display:block; border:0;"></td>
		<td width="1" height="43">
			<img src={"spacer-top.jpg"|ezimage}width="1" height="43" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="141" height="48" rowspan="2">
			<img src={"mailingtest/EzNova_09.jpg"|ezimage} width="141" height="48" alt="" style="display:block; border:0;"></td>
		<td width="1" height="21">
			<img src={"spacer-top.jpg"|ezimage}width="1" height="21" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="521" height="72" colspan="2" rowspan="2" bgcolor="#f6f6f6" valign="top">
			<div style="font-size:14px; color:#434343; width:450px;">eZ Systems travaille dans le secteur des solutions de gestion de contenu Web depuis 1999. Nous sommes présents partout en Europe, en Asie et en Amérique.</div></td>
		<td width="1" height="27">
			<img src={"spacer-top.jpg"|ezimage}width="1" height="27" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="141" height="45">
			<img src={"mailingtest/EzNova_11.jpg"|ezimage} width="141" height="45" alt="" style="display:block; border:0;"></td>
		<td width="1" height="45">
			<img src={"spacer-top.jpg"|ezimage}width="1" height="45" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="662" height="5" colspan="3">
			<img src={"mailingtest/EzNova_12.jpg"|ezimage} width="662" height="5" alt="" style="display:block; border:0;"></td>
		<td width="1" height="5">
			<img src={"spacer-top.jpg"|ezimage}width="1" height="5" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="700" height="27" colspan="5">
			<img src={"mailingtest/EzNova_13.jpg"|ezimage} width="700" height="27" alt="" style="display:block; border:0;"></td>
		<td width="1" height="27">
			<img src={"spacer-top.jpg"|ezimage}width="1" height="27" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="221" height="1127" colspan="2">
				<table id="Tableau_02" width="221" height="1127" border="0" cellpadding="0" cellspacing="0" style="color: #434343; font-family:Verdana, Geneva, sans-serif; font-size:14px;">
                  <tr>
                    <td width="17" height="1127" rowspan="10"><img src={"mailingtest/EzNova_somaire_01.jpg"|ezimage} width="17" height="1127" alt="" style="display:block; border:0;"></td>
                    <td width="187" height="50" valign="top"><div style="color:#e46809; font-size:24px;">SOMMAIRE</div></td>
                    <td width="17" height="1127" rowspan="10"><img src={"mailingtest/EzNova_somaire_03.jpg"|ezimage} width="17" height="1127" alt="" style="display:block; border:0;"></td>
                  </tr>
                  <tr>
                    <td width="187" height="341" valign="top"><div style="padding-bottom:5px; border-bottom:1px solid #999; color:#434343;">10th Annual eZ Systems Conference & Awards 2012</div>
                      <div style="padding:4px 0; border-bottom:1px solid #999; color:#434343;">Vidéos de démonstration</div>
                      <div style="padding:4px 0; border-bottom:1px solid #999; color:#434343;">PR: eZ Systems et Deutsche Telekom</div>
                      <div style="padding:4px 0; border-bottom:1px solid #999; color:#434343;">10th Annual eZ Systems Conference & Awards 2012</div>
                      <div style="padding:4px 0; border-bottom:1px solid #999; color:#434343;">Vidéos de démonstration</div>
                      <div style="padding:4px 0; color:#434343;">PR: eZ Systems et Deutsche Telekom</div></td>
                  </tr>
                  <tr>
                    <td width="187" height="89"><img src={"mailingtest/EzNova_somaire_05.jpg"|ezimage} width="187" height="89" alt="" style="display:block; border:0;"></td>
                  </tr>
                  <tr>
                    <td width="187" height="31"><img src={"mailingtest/EzNova_somaire_06.jpg"|ezimage} width="187" height="31" alt="" style="display:block; border:0;"></td>
                  </tr>
                  <tr>
                    <td width="187" height="88"><img src={"mailingtest/EzNova_somaire_07.jpg"|ezimage} width="187" height="88" alt="" style="display:block; border:0;"></td>
                  </tr>
                  <tr>
                    <td width="187" height="30"><img src={"mailingtest/EzNova_somaire_08.jpg"|ezimage} width="187" height="30" alt="" style="display:block; border:0;"></td>
                  </tr>
                  <tr>
                    <td width="187" height="89"><img src={"mailingtest/EzNova_somaire_09.jpg"|ezimage} width="187" height="89" alt="" style="display:block; border:0;"></td>
                  </tr>
                  <tr>
                    <td width="187" height="44"><img src={"mailingtest/EzNova_somaire_10.jpg"|ezimage} width="187" height="44" alt="" style="display:block; border:0;"></td>
                  </tr>
                  <tr>
                    <td width="187" height="31" valign=""><img src={"mailingtest/EzNova_somaire_11.jpg"|ezimage} width="43" height="20" alt="" style="border:0;"><a href={"mailing/unregister/"|ezurl} target="_blank" style="color:#e46809;">{"Unsubscribe from the mailing list."|i18n( 'extension/ezmailing/text' )}</a></td>
                  </tr>
                  <tr>
                    <td width="187" height="334"></td>
                  </tr>
                </table>	

        </td>
		<td width="479" height="1127" colspan="3">
			<table id="Tableau_03" width="479" height="1128" border="0" cellpadding="0" cellspacing="0" style="font-family:Verdana, Geneva, sans-serif; font-size:14px; color: #434343;">
  <tr>
    <td width="28" height="1127" rowspan="14"><img src={"mailingtest/EzNova_content_01.jpg"|ezimage} width="28" height="1127" alt="" style="display:block; border:0;"></td>
    <td width="422" height="3" colspan="4"><img src={"mailingtest/EzNova_content_02.jpg"|ezimage} width="422" height="3" alt="" style="display:block; border:0;"></td>
    <td width="29" height="1127" rowspan="14"><img src={"mailingtest/EzNova_content_03.jpg"|ezimage} width="29" height="1127" alt="" style="display:block; border:0;"></td>
  </tr>
  
  
  <!-- CONTENT -->
  <tr>
  	<td valign="top" colspan="3">
  		{$module_result.content}
  	</td>
  </tr>
  <!-- 
  <tr>
    <td width="252" height="21" colspan="3" style="color:#fff;" bgcolor="#4aa0aa" valign="top">&nbsp; RUBRIQUE</td>
    <td width="170" height="21"><img src={"mailingtest/EzNova_content_05.jpg"|ezimage} width="170" height="21" alt="" style="display:block; border:0;"></td>
  </tr>
  <tr>
    <td width="422" height="95" colspan="4" valign="top"><div style="font-size:24px;">10th Annual eZ Systems <br />
        Conference & Awards 2012</div>
      <div style="color:#e46809; font-size:12px;">Du 17 au 19 Octobre à Cologne</div></td>
  </tr>
  <tr>
    <td width="422" height="200" colspan="4"><img src={"mailingtest/EzNova_content_07.jpg"|ezimage} width="422" height="200" alt="" style="display:block; border:0;"></td>
  </tr>
  <tr>
    <td width="422" height="206" colspan="4" valign="top" ><div style="color:#434343">Freedom to Create Your Experience - The Road to Kilimanjaro, eZ Publish Release 5
        Digitize your business, optimize customer experience, embrace the power of the cloud!</div>
      <br>
      <div style="color:#434343;">This year's conference will be attended by industry professionals and experts in their field from the entire eZ Ecosystem and beyond. It is a must if you want to learn more about the latest trends and developments from both a business and developer perspective.</div></td>
  </tr>
  <tr>
    <td width="422" height="133" colspan="4" valign="top"><div style="margin:0 0 10px 60px;"><img src={"mailingtest/puce.jpg"|ezimage} width="14" height="10" alt="" style="border:0;">Learn how enterprises around the world</div>
      <div style="margin:0 0 10px 60px;"><img src={"mailingtest/puce.jpg"|ezimage} width="14" height="10" alt="" style="border:0;">Building sustainable digital businesses</div>
      <div style="margin:0 0 10px 60px;"><img src={"mailingtest/puce.jpg"|ezimage} width="14" height="10" alt="" style="border:0;">How the impact of mobile growth</div>
      <div style="margin:0 0 10px 60px;"><img src={"mailingtest/puce.jpg"|ezimage} width="14" height="10" alt="" style="border:0;">Cloud services will impact your future.</div></td>
  </tr>
  -->
  
  <!-- FIN CONTENT -->
  
  
  {if $module_result.content_info.persistent_variable.mailing_type|eq('folder')}
  <tr>
    <td width="422" height="31" colspan="4"><img src={"mailingtest/EzNova_content_10.jpg"|ezimage} width="422" height="31" alt="" style="display:block; border:0;"></td>
  </tr>
  <tr>
    <td width="250" height="20" colspan="2" bgcolor="#4aa0aa" valign="top" style="color:#fff">&nbsp; RUBRIQUE </td>
    <td width="172" height="29" colspan="2" rowspan="2"><img src={"mailingtest/EzNova_content_12.jpg"|ezimage} width="172" height="29" alt="" style="display:block; border:0;"></td>
  </tr>
  <tr>
    <td width="250" height="9" colspan="2"><img src={"mailingtest/EzNova_content_13.jpg"|ezimage} width="250" height="9" alt="" style="display:block; border:0;"></td>
  </tr>
  <tr>
    <td width="189" height="175" valign="top" align="left"><img src={"mailingtest/EzNova_content_14.jpg"|ezimage} width="170" height="141" alt="" style="display:block; border:0;"></td>
    <td width="233" height="175" colspan="3" valign="top"><div style="font-size:18px;">Vidéos de démonstration d'eZ Market</div>
      <div style="color:#e46809; font-size:12px;">22/06/2012</div>
      <div style="color:#434343; font-size:.97em;"> L'eZ Market, la place de marché d'eZ Systems, est l'endroit où les clients d'eZ Publish trouvent des extensions pour leurs installations. </div></td>
  </tr>
  <tr>
    <td width="422" height="29" colspan="4"><img src={"mailingtest/EzNova_content_16.jpg"|ezimage} width="422" height="29" alt="" style="display:block; border:0;"></td>
  </tr>
  <tr>
    <td width="250" height="20" colspan="2" bgcolor="#c5d100" valign="top" style="color:#fff">&nbsp; RUBRIQUE </td>
    <td width="172" height="20" colspan="2"><img src={"mailingtest/EzNova_content_18.jpg"|ezimage} width="172" height="20" alt="" style="display:block; border:0;"></td>
  </tr>
  <tr>
    <td width="422" height="10" colspan="4"><img src={"mailingtest/EzNova_content_19.jpg"|ezimage} width="422" height="10" alt="" style="display:block; border:0;"></td>
  </tr>
  <tr>
    <td width="189" height="175" valign="top" align="left"><img src={"mailingtest/EzNova_content_20.jpg"|ezimage} width="170" height="139" alt="" style="display:block; border:0;"></td>
    <td width="233" height="175" colspan="3" valign="top"><div style="font-size:18px;">Vidéos de démonstration d'eZ Market</div>
      <div style="color:#e46809; font-size:12px;">22/06/2012</div>
      <div style="color:#434343; font-size:.97em;"> L'eZ Market, la place de marché d'eZ Systems, est l'endroit où les clients d'eZ Publish trouvent des extensions pour leurs installations. </div></td>
  </tr>
  <tr>
    <td width="28" height="1"><img src={"spacer-top.jpg"|ezimage} width="28" height="1" alt="" style="display:block; border:0;"></td>
    <td width="189" height="1"><img src={"spacer-top.jpg"|ezimage} width="189" height="1" alt="" style="display:block; border:0;"></td>
    <td width="61" height="1"><img src={"spacer-top.jpg"|ezimage} width="61" height="1" alt="" style="display:block; border:0;"></td>
    <td width="2" height="1"><img src={"spacer-top.jpg"|ezimage} width="2" height="1" alt="" style="display:block; border:0;"></td>
    <td width="170" height="1"><img src={"spacer-top.jpg"|ezimage} width="170" height="1" alt="" style="display:block; border:0;"></td>
    <td width="29" height="1"><img src={"spacer-top.jpg"|ezimage} width="29" height="1" alt="" style="display:block; border:0;"></td>
  </tr>
  {/if}
</table>
            </td>
		<td width="1" height="1127">
			<img src={"spacer-top.jpg"|ezimage} width="1" height="1127" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="700" height="52" colspan="5">
			<img src={"mailingtest/EzNova_16.jpg"|ezimage} width="700" height="52" alt="" style="display:block; border:0;"></td>
		<td width="1" height="52">
			<img src={"spacer-top.jpg"|ezimage} width="1" height="52" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="700" height="210" colspan="5">
			<table id="Tableau_04" width="700" height="210" border="0" cellpadding="0" cellspacing="0" bgcolor="#f6f6f6" style="font-size:14px; color:#434343; font-family:Verdana, Geneva, sans-serif; color: #434343;">
	<tr>
		<td width="700" height="22" colspan="7">
			<img src={"mailingtest/EzNova_footer_01.jpg"|ezimage} width="700" height="22" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="20" height="188" rowspan="2">
			<img src={"mailingtest/EzNova_footer_02.jpg"|ezimage} width="20" height="188" alt="" style="display:block; border:0;"></td>
		<td width="204" height="88">
			<img src={"mailingtest/EzNova_footer_03.jpg"|ezimage} width="204" height="88" alt="" style="display:block; border:0;"></td>
		<td width="25" height="188" rowspan="2">
			<img src={"mailingtest/EzNova_footer_04.jpg"|ezimage} width="25" height="188" alt="" style="display:block; border:0;"></td>
		<td width="204" height="88">
			<img src={"mailingtest/EzNova_footer_05.jpg"|ezimage} width="204" height="88" alt="" style="display:block; border:0;"></td>
		<td width="23" height="188" rowspan="2">
			<img src={"mailingtest/EzNova_footer_06.jpg"|ezimage} width="23" height="188" alt="" style="display:block; border:0;"></td>
		<td width="204" height="88">
			<img src={"mailingtest/EzNova_footer_07.jpg"|ezimage} width="204" height="88" alt="" style="display:block; border:0;"></td>
		<td width="20" height="188" rowspan="2">
			<img src={"mailingtest/EzNova_footer_08.jpg"|ezimage} width="20" height="188" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="204" height="100" valign="top">
			<a href="#" style="color:#ef881b">LIENS 1</a><br>
            <div>Business Marketplace</div>
            </td>
		<td width="204" height="100" valign="top">
			<a href="#" style="color:#ef881b">LIENS 1</a><br>
            <div>Business Marketplace</div>
            </td>
		<td width="204" height="100" valign="top">
			<a href="#" style="color:#ef881b">LIENS 1</a><br>
            <div>Business Marketplace</div>
            </td>
	</tr>
    
</table>
            
            </td>
		<td width="1" height="210">
			<img src={"spacer-top.jpg"|ezimage} width="1" height="210" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="700" height="82" colspan="5" valign="top" align="center">
        <br>
			<div style="color:#434343;"><a href="#WEBVIEW_LINK#" target="_blank" style="color:#e46809;">{"If you have trouble viewing this email, read the online version."|i18n( 'extension/ezmailing/text' )}</a>&nbsp; | &nbsp;<a href={"mailing/unregister/"|ezurl} target="_blank" style="color:#e46809;">{"Unsubscribe from the mailing list."|i18n( 'extension/ezmailing/text' )}</a></div></td>
		<td width="1" height="82">
			<img src={"spacer-top.jpg"|ezimage} width="1" height="82" alt="" style="display:block; border:0;"></td>
	</tr>
	<tr>
		<td width="16" height="1">
			<img src={"spacer-top.jpg"|ezimage} width="16" height="1" alt="" style="display:block; border:0;"></td>
		<td width="205" height="1">
			<img src={"spacer-top.jpg"|ezimage} width="205" height="1" alt="" style="display:block; border:0;"></td>
		<td width="316" height="1">
			<img src={"spacer-top.jpg"|ezimage} width="316" height="1" alt="" style="display:block; border:0;"></td>
		<td width="141" height="1">
			<img src={"spacer-top.jpg"|ezimage} width="141" height="1" alt="" style="display:block; border:0;"></td>
		<td width="22" height="1">
			<img src={"spacer-top.jpg"|ezimage} width="22" height="1" alt="" style="display:block; border:0;"></td>
		<td width="1" height="1"></td>
	</tr>
</table>
<!-- End Save for Web Slices -->
</body>
</html>