{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $lists  = fetch('mailing','fetch',hash(
                                                   'type','orphanusers',
                                                   'limit', 10,
                                                   'sort_by', hash( 'registred', 'desc')
                                               )
                          )
    $action = cond( is_set($action),$action,true(),"mailing/users")
}
    {include uri="design:mailing/list/users.tpl" lists=$lists orphanMode=true() action=$action  blockid="last_orphan_users" show_search_form=false()}
{undef $lists $action}