{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $lists = fetch('mailing','fetch',hash(
                                                       'type','registrations',
                                                       'filter', hash(
                                                                        'state', $state
                                                                       ),
                                                       'limit', 10,
                                                       'sort_by', hash('registred','desc')
                                                   )
                              )
    $action = cond( is_set($action),$action,true(),"mailing/registrations")
    $blockid= concat("last_registrations_state_", $state)
}
    {if is_array($state)}
        {set $blockid = "last_registrations_state_"}
        {foreach $state as $state_item}
            {if is_array($state)}
                {set $blockid = $blockid|concat($state_item|implode('_'))}
            {else}
                {set $blockid = $blockid|concat($state_item)}
            {/if}
        {/foreach}
    {/if}
    
    {include uri="design:mailing/list/registrations.tpl" lists=$lists action=$action blockid=$blockid show_search_form=false() state_filter=$state edit=false() embed=true()}
{undef $lists $action $blockid}