{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def
    $lists = fetch('mailing','fetch',hash(
                                                       'type','campaigns',
                                                       'filter',cond( is_set($state), hash( 'state',$state), true(), hash() ),
                                                       'limit',10,
                                                       'sort_by', hash( 'state_updated', 'desc')
                                                   )

                              )
    $action = cond( is_set($action),$action,true(),"mailing/campaigns")
    $blockid= concat("last_campaigns_state_", $state)
}
    {if is_array($state)}
        {set $blockid = "last_campaigns_state_"}
        {foreach $state as $state_item}
            {if is_array($state)}
                {set $blockid = $blockid|concat($state_item|implode('_'))}
            {else}
                {set $blockid = $blockid|concat($state_item)}
            {/if}
        {/foreach}
    {/if}

    {include uri="design:mailing/list/campaigns.tpl" lists=$lists action=$action blockid=$blockid show_search_form=false() embed=true()}
{undef $lists $action $blockid}
