{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="ezmailing_header" class="registrations_list_header">
    <h1>{$title}</h1>
	<p id="ezmailing_header_text">
         {"List of mailings lists registrations. Use filters to display specific registration state."|i18n( 'extension/ezmailing/text' )}
    </p>
	<div class="clear"></div>
</div>