system:
    cg77_front:
        ezpage:
            layouts:
                NewsletterZonesLayout:
                    name: "Zone Newsletter"
                    template: "CGNewsletterBundle:eZFlow/Zones:newsletterZonesLayout.html.twig"
            enabledLayouts: [NewsletterZonesLayout]
            blocks:
                bloc_newsletter_a_la_une_insert:
                    name: "Bloc newsletter à la une"
                bloc_newsletter_bref_insert:
                    name: "Bloc newsletter  en bref"
                bloc_newsletter_actus_insert:
                    name: "Bloc newsletter actualitéss"
                bloc_newsletter_invitation_insert:
                    name: "Bloc newsletter invitation"