system:
    cg77_front:
        image_variations:
            newsletter_la_une:
                reference: reference
                filters:
                    - { name: geometry/scalewidth, params: [420] }
            newsletter_actus:
                reference: reference
                filters:
                    - { name: geometry/scalewidth, params: [79] }
            newsletter_invitation:
                reference: reference
                filters:
                    - { name: geometry/scalewidth, params: [634] }