system:
    cg77_front:
        location_view:
            full:
                newsletter:
                    template: CGNewsletterBundle:Full:gabarit.html.twig
                    match:
                        Identifier\ContentType: [newsletter]
                        Identifier\Section: [standard]
        block_view:
            bloc_a_la_une:
                template: "CGNewsletterBundle:eZFlow/Blocks:la_une.html.twig"
                match:
                    Type: bloc_newsletter_a_la_une_insert
            bloc_bref:
                template: "CGNewsletterBundle:eZFlow/Blocks:bref.html.twig"
                match:
                    Type: bloc_newsletter_bref_insert
            bloc_actus:
                template: "CGNewsletterBundle:eZFlow/Blocks:actus.html.twig"
                match:
                    Type: bloc_newsletter_actus_insert
            bloc_invitation:
                template: "CGNewsletterBundle:eZFlow/Blocks:invitation.html.twig"
                match:
                    Type: bloc_newsletter_invitation_insert
