{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if and(is_set($errors),$errors|count|gt(0))}
	<div class="message-error">
	    <h2><span class="time">[{currentdate()|l10n( 'shortdatetime' )}]</span> {if is_set($title_errors)}{$title_errors}{else}{'This item could not be stored.'|i18n( 'extension/ezmailing/text' )}{/if}</h2>
	    <ul>
	    {foreach $errors as $error}
	        <li>{$error}</li>
	    {/foreach}
	    <ul>
	</div>
{/if}


{if is_set($success_message)}
    <div class="message-feedback">
        <h2><span class="time">[{currentdate()|l10n( 'shortdatetime' )}]</span> {$success_message}</h2>
    </div>
{/if}