{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="ezmailing_header" class="edit">
	<div id="ezmailing_header_status">
	{if is_set($subaction)}
		{if and($item.is_draft_succeed,$item.is_tested_succeed|not())}
		<div id="ezmailing_header_tested_status">
			<p>{"Tested"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_tested_state.png"|ezimage()} width="55" height="55" alt="{"Tested"|i18n('extension/ezmailing/text')}" />
		</div>
		{elseif and($item.is_tested_succeed,$item.is_confirmed_succeed|not())}
		<div id="ezmailing_header_confirmed_status">
			<p>{"Confirmed"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_confirmed_state.png"|ezimage()} width="55" height="55" alt="{"Confirmed"|i18n('extension/ezmailing/text')}" />
		</div>
		{elseif and($item.is_confirmed_succeed,$item.is_waiting_for_send_succeed|not())}
		<div id="ezmailing_header_waiting_status">
			<p>{"Waiting"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_waiting_state.png"|ezimage()} width="55" height="55" alt="{"Waiting"|i18n('extension/ezmailing/text')}" />
		</div>
		{elseif and($item.is_waiting_for_send_succeed,$item.is_sending_in_progress_succeed|not())}
		<div id="ezmailing_header_sending_status">
			<p>{"Sending"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_sending_state.png"|ezimage()} width="55" height="55" alt="{"Sending"|i18n('extension/ezmailing/text')}" />
		</div>
		{elseif $item.is_sent}
		<div id="ezmailing_header_sent_status">
			<p>{"Sent"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_sent_state.png"|ezimage()} width="55" height="55" alt="{"Sent"|i18n('extension/ezmailing/text')}" />
		</div>
		{elseif $item.is_cancelled}
		<div id="ezmailing_header_cancelled_status">
			<p>{"Cancelled"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_cancelled_state.png"|ezimage()} width="55" height="55" alt="{"Cancelled"|i18n('extension/ezmailing/text')}" />
		</div>
		{elseif $item.is_deleted}
		<div id="ezmailing_header_deleted_status">
			<p>{"Deleted"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_deleted_state.png"|ezimage()} width="55" height="55" alt="{"Deleted"|i18n('extension/ezmailing/text')}" />
		</div>
		{else}
		<div id="ezmailing_header_draft_status">
			<p>{"Draft"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_draft_state.png"|ezimage()} width="55" height="55" alt="{"Draft"|i18n('extension/ezmailing/text')}" />
		</div>
		{/if}				
	{/if}
	</div>
    <h1>{$title}</h1>
    <p id="ezmailing_header_text">
            {$item.description|wash}
    </p>
    <p id="ezmailing_header_update">
    	{"Last updated state date"|i18n( 'extension/ezmailing/text' )} : {$item.state_updated|l10n( 'shortdatetime' )}
    </p>
	<div class="clear"></div>	        
</div>