{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="ezmailing_header">
	<form {if is_set($action)} action={$action|ezurl} {/if} method="post" name="campaignlistform{if is_set($blockid)}_{$blockid}{/if}">
        <h1>{$title}</h1>
        <input type="submit" name="CreateCampaignButton" title="{"Create new campaign"|i18n( 'extension/ezmailing/text' )}" value="{"Create new campaign"|i18n( 'extension/ezmailing/text' )}" />
		<p id="ezmailing_header_text">
            {"List of existing campaigns. Use filters to display a quicker look of the campaign states."|i18n( 'extension/ezmailing/text' )}
        </p>
	</form>
	<div class="clear"></div>
</div>