{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="ezmailing_header" class="send">
	<div id="ezmailing_header_status">
	{if is_set($subaction)}
		{if and( $item.is_draft_succeed, $item.is_tested_succeed|not(), $item.is_cancelled|not(), $item.is_deleted|not() )}
		<div id="ezmailing_header_tested_status">
			<p>{"Tested"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_tested_state.png"|ezimage()} width="55" height="55" alt="{"Tested"|i18n('extension/ezmailing/text')}" />
		</div>
		{elseif and( $item.is_tested_succeed, $item.is_confirmed_succeed|not(), $item.is_cancelled|not(), $item.is_deleted|not() )}
		<div id="ezmailing_header_confirmed_status">
			<p>{"Confirmed"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_confirmed_state.png"|ezimage()} width="55" height="55" alt="{"Confirmed"|i18n('extension/ezmailing/text')}" />
		</div>
		{elseif and( $item.is_confirmed_succeed, $item.is_waiting_for_send_succeed|not(), $item.is_cancelled|not(), $item.is_deleted|not() )}
		<div id="ezmailing_header_waiting_status">
			<p>{"Waiting"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_waiting_state.png"|ezimage()} width="55" height="55" alt="{"Waiting"|i18n('extension/ezmailing/text')}" />
		</div>
		{elseif and( $item.is_waiting_for_send_succeed, $item.is_sending_in_progress_succeed|not(), $item.is_cancelled|not(), $item.is_deleted|not() )}
		<div id="ezmailing_header_sending_status">
			<p>{"Sending"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_sending_state.png"|ezimage()} width="55" height="55" alt="{"Sending"|i18n('extension/ezmailing/text')}" />
		</div>
		{elseif $item.is_sent}
		<div id="ezmailing_header_sent_status">
			<p>{"Sent"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_sent_state.png"|ezimage()} width="55" height="55" alt="{"Sent"|i18n('extension/ezmailing/text')}" />
		</div>
		{elseif $item.is_cancelled}
		<div id="ezmailing_header_cancelled_status">
			<p>{"Cancelled"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_cancelled_state.png"|ezimage()} width="55" height="55" alt="{"Cancelled"|i18n('extension/ezmailing/text')}" />
		</div>
		{elseif $item.is_deleted}
		<div id="ezmailing_header_deleted_status">
			<p>{"Deleted"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_deleted_state.png"|ezimage()} width="55" height="55" alt="{"Deleted"|i18n('extension/ezmailing/text')}" />
		</div>
		{else}
		<div id="ezmailing_header_draft_status">
			<p>{"Draft"|i18n('extension/ezmailing/text')}</p>
			<img src={"pictos/header_draft_state.png"|ezimage()} width="55" height="55" alt="{"Draft"|i18n('extension/ezmailing/text')}" />
		</div>
		{/if}				
	{/if}
	</div>
    <h1>{$title}</h1>
    <p id="ezmailing_header_text">
            {$item.description|wash}
    </p>
    <p id="ezmailing_header_update" class="ezmailing_header_update_tooltip">
        {'Sending Date'|i18n( 'extension/ezmailing/text' )} {$item.sending_date|l10n( 'shortdatetime' )}
        <a href="#" title="{'Sending Date'|i18n( 'extension/ezmailing/text' )}">
            <img    src={"pictos/header_clock.png"|ezimage()}
                            width="23"
            height="22"
            alt="{'Sending Date'|i18n( 'extension/ezmailing/text' )}" />
        </a>
            <span class="ezmailing_tooltip">
                <span>{"Last updated state date"|i18n( 'extension/ezmailing/text' )} : {$item.state_updated|l10n( 'shortdatetime' )}</span>
            </span>
    </p>
	<div class="clear"></div>
    <div id="ezmailing_header_details"{if $item.is_sent} class="is_sent"{/if}>
    	<div id="left_details">
    		<p>
    			<strong>{"Sender"|i18n('extension/ezmailing/text')}</strong> : {$item.sender_name|wash} ({$item.sender_email|wash})
    		</p>
    		<p>
    			<strong>{"URL"|i18n('extension/ezmailing/text')}</strong> : <a href="{$item.campaign_url|wash}" target="_blank">{$item.campaign_url|wash}</a>
    		</p>
    		<p>
    			<strong>{"Content"|i18n( 'extension/ezmailing/text' )}</strong> : 
    			{def $contentNode = fetch( 'content', 'node', hash( 'node_id',$item.node_id ))}
    			{if and( $item.state|ne( '99' ), $contentNode )}
		            <a href={$contentNode.url_alias|ezurl}>{$contentNode.name|wash}</a>
		        {else}
		        	<span>{"Static"|i18n('extension/ezmailing/text')}</span>
		        {/if}
		        {undef $contentNode}
    		</p>
    	</div>
    	<div id="right_details">
    		<p>
    			<strong>{"Created"|i18n( 'extension/ezmailing/text' )}</strong> : {$item.created|l10n( 'shortdatetime' )}
    		</p>
    		<p>
    			<strong>{"Updated"|i18n( 'extension/ezmailing/text' )}</strong> : {$item.updated|l10n( 'shortdatetime' )}
    		</p>
    	</div>
    	<div class="clear"></div>
    </div>
    <div class="clear"></div>
    <div id="grabber">
    	<a href="#" title="{"AFFICHER/CACHER DETAILS"|i18n( 'extension/ezmailing/text' )}">
    		<img src={"pictos/grabber.png"|ezimage()} width="38" height="15" />
    	</a>
    </div>
</div>