{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="ezmailing_header"  class="statistics_header">
	<h1>{"Statistics"|i18n('extension/ezmailing/text')}</h1>
    <div class="clear"></div>
</div>