{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="ezmailing_registration">
    <div class="attribute-header">
        <h2>{'Register'|i18n( 'extension/ezmailing/text' )}</h2>
    </div>
    <form method="post" action={"mailing/register"|ezurl} >
        {def
            $email = cond( is_set( $fields.Email ), $fields.Email, true(), '')
            $MailingListID = cond( is_set( $fields.MailingListID ), $fields.MailingListID, true(), array() )
            $lists = fetch('mailing','fetch',hash(
                                                    'type','mailinglist',
                                                    'sort_by', hash( 'name', 'asc')
                                                 ))
            $attributes = ezini( 'MailingUserAccountSettings', 'Attributes', 'ezmailing.ini' )
            $templateAttribute = ""
            $requires 			= ezini( 'MailingUserAccountSettings', 'RequiredAttributes', 'ezmailing.ini' )
        }

        {* handle attributes *}
        {foreach $attributes as $identifier => $label}
            {set $templateAttribute = concat( 'design:mailing/users/attributes/', $identifier, '.tpl' )}

            {include uri=$templateAttribute edit=true() requires=$requires}
           {* <div class="block">
                <label>{$label|i18n( 'extension/ezmailing/text' )}:</label>
                <input type="text" name="{$identifier}" value="" />
            </div>
             *}
        {/foreach}
        {undef
            $attributes
            $requires
        }

        <ul>
        {foreach $lists as $mailing}
            <li><label><input type="checkbox" {if $MailingListID|contains($mailing.id)} checked="checked" {/if} value="{$mailing.id}" name="MailingListID[]" />{$mailing.name|wash}</label></li>
        {/foreach}
        </ul>
        {undef $lists $email $MailingListID}
        <input type="submit" class="button"  name="MailingRegisterButton" value={'Register'|i18n( 'extension/ezmailing/text' )} />
    </form>
</div>