{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if is_set($errors)}
    <div class="message-error">
        <h2><span class="time">[{currentdate()|l10n( shortdatetime )}]</span> {'The registration could not be made.'|i18n( 'extension/ezmailing/text' )}</h2>
            <p>{"Input is not valid."|i18n("design/standard/content/edit")}</p>
            <ul>
                {foreach $errors as $error}
                    <li>{$error|wash}</li>
                {/foreach}
            </ul>
    </div>
{/if}

{if is_set($confirmation)}
<div class="feedback">
    <h2>{$confirmation|wash}</h2>
    {if is_set($mailingListNames)}
        <p>{"For mailing lists: "|i18n("extension/ezmailing/text")}</p>
        <ul>
            {foreach $mailingListNames as $mailingListName}
                <li>{$mailingListName}</li>
            {/foreach}
        </ul>
    {/if}
</div>
{/if}