{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if $node|is_campaign}
    {def $connectedCampaigns = $node|get_campaigns}

        {set scope=global persistent_variable=hash('mailing_subject', concat('GENERIC: ',$node.name|wash), 'mailing_date',  'date format'  )}


        {*
            You can get, the subject, the description or anything else about the Campaign
            {$connectedCampaigns|attribute('show',2)}
        *}
View Mailing

Create here your template to show your campaign/mailing.

The best practice is to set a new override to handle the good template.

    {undef $connectedCampaigns}

{else}

It's not connected to a Campaign

{/if}