    {* DO NOT EDIT THIS FILE! Use an override template instead. *}
<h2>{'Affect to a mailing list'|i18n( 'extension/ezmailing/text' )}</h2>
<div id="ezmailing_record_list">
    <ul>
    {foreach $lists as $item sequence array('bglight', 'bgdark') as $seq}
        <li class="ezmailing_list_item ezmailing_import">
            <p class="ezmailing_sending_date">
				<span>
					<strong>{'Registred'|i18n( 'extension/ezmailing/text' )}
                        : </strong>{$item.created|l10n( 'shortdatetime' )}
				</span>
				<span>
					<strong>{'Changed'|i18n( 'extension/ezmailing/text' )}
                        : </strong>{$item.updated|l10n( 'shortdatetime' )}
				</span>
            </p>

            <div class="ezmailing_user_email">
                <h3>
                    <a href={$item.url|ezurl}>{$item.name|wash}</a>
                </h3>
                {if $item.is_importing}
                    <p>{"An import is currently running on..."|i18n( 'extension/ezmailing/text' )}</p>
                {/if}
                {if $item.is_synchronizing}
                    <p>{"A synchronisazion is currently running on..."|i18n( 'extension/ezmailing/text' )}</p>
                {/if}
            </div>
            <div class="ezmailing_mailing_lists_registration">
                <p class="mailing_list_registrations_count">
                    <span>{$item.registrations_count}</span>{'registrations'|i18n( 'extension/ezmailing/text' )}
                </p>
            </div>
            <div class="ezmailing_import_lang">
                <p>
                    <img src="{$item.lang|flag_icon}" width="18" height="12" alt="{$item.lang}"/>
                </p>
            </div>
            {if $item.is_available}
                <div class="ezmailing_checkbox_button">
                    <table cellpadding="0" cellspacing="0">
                        <tr>
                            <td>
                                <input type="checkbox"
                                       name="itemsActionCheckbox[]"
                                       value="{$item.id}"
                                       class="jqTransformField"
                                        />
                            </td>
                        </tr>
                    </table>
                </div>
            {/if}
            <div class="clear"></div>
        </li>
    {/foreach}
    </ul>
</div>