{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="ezmailing_container" class="ezmailing_mailinglists_container">
    <div id="ezmailing_content">
        <h2>{"Mailing List"|i18n('extension/ezmailing/text')}</h2>
        <div id="ezmailing_search_form">
            <form   method="post" 
		            name="campaignlistfeatures" 
		            id="campaignlistfeatures"
		            class="jqTransform">
		        <div id="ezmailing_sort">
		        	<h3>{'Order by'|i18n( 'extension/ezmailing/text' )}</h3>
		            <select name="order_field" 
		                    id="order_field" 
		                    info="{'Please select order field'|i18n( 'extension/ezmailing/text' )}"
		                    class="jqTransformField customCss">
		                <option value="#">
		                    {'ORDER BY'|i18n( 'extension/ezmailing/text' )}
		                </option>
		                <option value="name"
		                        dir="asc"
		                        {if $view_parameters.order_field|eq("name")}
		                            selected="selected"
		                        {/if}>
		                    {'NAME'|i18n( 'extension/ezmailing/text' )}
		                </option>
		                <option value="created"
		                        dir="desc"
		                        {if $view_parameters.order_field|eq("created")}
		                            selected="selected"
		                        {/if}>
		                    {'CREATED'|i18n( 'extension/ezmailing/text' )}
		                </option>
		                <option value="updated"
		                        dir="desc"
		                        {if $view_parameters.order_field|eq("updated")}
		                            selected="selected"
		                        {/if}>
		                    {'UPDATED'|i18n( 'extension/ezmailing/text' )}
		                </option>
		            </select>
		        </div>
		        <div id="ezmailing_search">
		        	<h3>{'Search'|i18n( 'extension/ezmailing/text' )}</h3>
		            <p>
		                <input  type="text" 
		                        {if is_set($searched_text)}
		                            value="{$searched_text}" 
		                        {else}
		                            value="{'SEARCH'|i18n( 'extension/ezmailing/text' )}" 
		                        {/if}
		                        alt="{'SEARCH'|i18n( 'extension/ezmailing/text' )}" 
		                        name="SearchMailingListText" 
		                        id="ezmailing_search_text" 
		                        class="switchValue" />
		                <input  type="submit" 
		                        value="" 
		                        name="SearchMailingListButton" 
		                        id="ezmailing_search_ok" />
		            </p>
		        </div>
		    </form>
        </div>        
        <div id="ezmailing_record_list">
            <form 	{if is_set($action)}
                    action={$action|ezurl}
					{/if} method="post"
					name="mailinglistsform"
                	class="jqTransform">
                {if is_set($searched_text)}<h2>{$lists|count} {"Results for « %search_text »"|i18n( 'extension/ezmailing/text', '', hash( '%search_text', $searched_text ) )}</h2>{/if}
                <ul>
                    {foreach $lists as $item sequence array('bglight', 'bgdark') as $seq}
                        <li class="ezmailing_list_item ezmailing_news">
                            <p class="ezmailing_sending_date">
                                <span>
                                	<strong>{'Created'|i18n( 'extension/ezmailing/text' )} : </strong> {$item.created|l10n( 'shortdatetime' )}
                                </span>
                                <span>
                                	<strong>{'Updated'|i18n( 'extension/ezmailing/text' )} : </strong> {$item.updated|l10n( 'shortdatetime' )}
                                </span>
                            </p>
                            <h3>
                                <a href={$item.url|ezurl}>{$item.name|wash}</a>
                            </h3>
                            {if $item.is_importing}
                                <p>{"An import is currently running on..."|i18n( 'extension/ezmailing/text' )}</p>
                            {/if}
                            {if $item.is_synchronizing}
                                <p>{"A synchronisazion is currently running on..."|i18n( 'extension/ezmailing/text' )}</p>
                            {/if}
                            <div class="clear"></div>
                            <div class="ezmailing_mailing_lists_registration">
                            	<p class="mailing_list_registrations_count">
									<span>{$item.registrations_count}</span>{'registrations'|i18n( 'extension/ezmailing/text' )}
								</p>
                            </div>                            
                            <div class="ezmailing_mailing_lists_registration">
                            	{if is_provided()}
                            	<p class="mailing_list_registrations_count">
									<span>{cond($item.remote_id|ne(''), $item.count_remote_registration, 'NA')}</span>{'Remote number of registrations'|i18n( 'extension/ezmailing/text' )}
								</p>
								{/if}
								&nbsp;
                            </div>                            
                            <div class="ezmailing_mailing_lists_lang">
                            	<img src="{$item.lang|flag_icon}" width="18" height="12" alt="{$item.lang}" />
                            	{$item.lang}
                            </div>
                            <div class="ezmailing_open_actions">
                                <a href="#">
                                    <span>{'Actions'|i18n( 'extension/ezmailing/text' )}</span>
                                    <img    src={"pictos/actions_down_arrow.png"|ezimage()} 
                                            width="44" 
                                            height="45" 
                                            alt="Actions" />
                                </a>
                            </div>
                            <div class="ezmailing_checkbox_button">
                                <table cellpadding="0" cellspacing="0">
                                    <tr>
                                        <td>
                                            <input	type="checkbox"
                                                    name="itemsActionCheckbox[]"
                                                    value="{$item.id}"
                                                    class="jqTransformField" />
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="ezmailing_actions_buttons">
                                <ul>
                                    <li class="edit_record">                                    	
                                        <a href={concat( '/mailing/mailinglists/edit/', $item.id )|ezurl}>{'Edit'|i18n( 'extension/ezmailing/text' )}</a>
                                    </li>
                                    {if $item.registrations_count|gt(0)}
                                    <li class="export_record">
                                        <a href={concat( "/mailing/export/Registration/(fix_item_type)/MailingList/(fix_item_id)/", $item.id )|ezurl}>{'Export'|i18n( 'extension/ezmailing/text' )}</a>
                                    </li>
                                    {/if}
                                    <li class="remove_record">
                                        <a href={concat( '/mailing/mailinglists/delete/', $item.id )|ezurl}>
                                            {'Remove'|i18n( 'extension/ezmailing/text' )}
                                        </a>
                                    </li>
                                </ul>
                                <div class="ezmailing_close_actions">
                                    <a href="#">
                                        <span>{'Close'|i18n( 'extension/ezmailing/text' )}</span>
                                        <img src={"pictos/actions_up_arrow.png"|ezimage()} width="44" height="45" alt="FERMER" />
                                    </a>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </li>
                    {/foreach}
                </ul>
                <div id="ezmailing_actions_submit">
                    <ul>
                        <li id="remove_selected">
                            <button     type="submit" 
                                        name="RemoveMailingListsButton" 
                                        title="{'Remove selected mailing lists.'|i18n( 'extension/ezmailing/text' )}"
                                        disabled="disabled">
                                {'Remove'|i18n( 'extension/ezmailing/text' )}<br />{'selected'|i18n( 'extension/ezmailing/text' )}
                            </button>
                        </li>
                        <li id="new_record">
							<button     type="submit" 
                                        name="CreateMailingListButton" 
                                        title="{'Create a mailing list.'|i18n( 'extension/ezmailing/text' )}">
                                {'Create new'|i18n( 'extension/ezmailing/text' )}<br />{'mailing list'|i18n( 'extension/ezmailing/text' )}
                            </button>
                        </li>
                        {if $lists|count|gt(0)}
                        <li id="export_campaign">
                            <a href={concat(   "mailing/export/MailingList/", 
                                                cond(   is_set( $state_filter ), $state_filter, 
                                                        is_set( $searched_text ), concat('search/', $searched_text), 
                                                        true(), '' 
                                                ),
                                                cond(	is_set( $suffix ), $suffix, false() )
                                        )|ezurl} title="{'CSV export'|i18n( 'extension/ezmailing/text' )}">
                                {'Export All'|i18n( 'extension/ezmailing/text' )}
                            </a>
                        </li>
                        {/if}
                    </ul>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
            </form>
        </div>
    </div>
</div>