{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def
	$show_registration_content	= or(	and(	is_set( $embed ), $embed ), is_unset( $embed)	)
	$show_edit					= or(	and(	is_set( $edit ), $edit	), is_unset( $edit )	)
}
{if is_unset($show_search_form)}
	{def $show_search_form = true()}
{/if}
{if $show_registration_content}
<div id="ezmailing_container" class="ezmailing_registrations_container">
    <div id="ezmailing_content">
		{if or( is_unset( $embed ), $embed|not() )}
		<h2>{"Registration list"|i18n('extension/ezmailing/text')}</h2>
		<div id="ezmailing_item_states">        
			<h3>{"Show only registrations with this selected state :"|i18n('extension/ezmailing/text')}</h3>
			<ul>
				<li id="registred">
					<a  href={"mailing/registrations/registred"|ezurl} 
						alt="{"Registred"|i18n('extension/ezmailing/text')}">
					{if and(is_set($subaction),$subaction|eq('registred'))}
						<img    src={"pictos/registred_state_on.png"|ezimage()} 
								width="55" 
								height="55" 
								alt="{"Registred"|i18n('extension/ezmailing/text')}"
								title="{"Registred"|i18n('extension/ezmailing/text')}" />
						<span>{"Registred"|i18n('extension/ezmailing/text')}</span>
					{else}
						<img    src={"pictos/registred_state_off.png"|ezimage()} 
								width="55" 
								height="55" 
								alt="{"Registred"|i18n('extension/ezmailing/text')}"
								title="{"Registred"|i18n('extension/ezmailing/text')}" />
						<span class="off">{"Registred"|i18n('extension/ezmailing/text')}</span>
					{/if}
					</a>
				</li>
				<li id="unregistred">
					<a href={"mailing/registrations/unregistred"|ezurl}>
						{if and(is_set($subaction),$subaction|eq('unregistred'))}
							<img    src={"pictos/unregistred_state_on.png"|ezimage()} 
									width="55" 
									height="55" 
									alt="{"Unregistred"|i18n('extension/ezmailing/text')}"
									title="{"Unregistred"|i18n('extension/ezmailing/text')}" />
							<span>{"Unregistred"|i18n('extension/ezmailing/text')}</span>
						{else}
							<img    src={"pictos/unregistred_state_off.png"|ezimage()} 
									width="55" 
									height="55" 
									alt="{"Unregistred"|i18n('extension/ezmailing/text')}"
									title="{"Unregistred"|i18n('extension/ezmailing/text')}" />
							<span class="off">{"Unregistred"|i18n('extension/ezmailing/text')}</span>
						{/if}
					</a>
				</li>
				<li id="blocked">
					<a href={"mailing/registrations/blocked"|ezurl}>
						{if and(is_set($subaction),$subaction|eq('blocked'))}
							<img    src={"pictos/blocked_state_on.png"|ezimage()} 
									width="55" 
									height="55" 
									alt="{"Blocked"|i18n('extension/ezmailing/text')}"
									title="{"Blocked"|i18n('extension/ezmailing/text')}" />
							<span>{"Blocked"|i18n('extension/ezmailing/text')}</span>
						{else}
							<img    src={"pictos/blocked_state_off.png"|ezimage()} 
									width="55" 
									height="55" 
									alt="{"Blocked"|i18n('extension/ezmailing/text')}"
									title="{"Blocked"|i18n('extension/ezmailing/text')}" />
							<span class="off">{"Blocked"|i18n('extension/ezmailing/text')}</span>
						{/if}
					</a>
				</li>
				<li id="softbounce">
					<a href={"mailing/registrations/softbounce"|ezurl}>
						{if and(is_set($subaction),$subaction|eq('softbounce'))}
							<img    src={"pictos/soft_bounce_state_on.png"|ezimage()} 
									width="55" 
									height="55" 
									alt="{"Soft bounce"|i18n('extension/ezmailing/text')}"
									title="{"Soft bounce"|i18n('extension/ezmailing/text')}" />
							<span>{"Soft bounce"|i18n('extension/ezmailing/text')}</span>
						{else}
							<img    src={"pictos/soft_bounce_state_off.png"|ezimage()} 
									width="55" 
									height="55" 
									alt="{"Soft bounce"|i18n('extension/ezmailing/text')}"
									title="{"Soft bounce"|i18n('extension/ezmailing/text')}" />
							<span class="off">{"Soft bounce"|i18n('extension/ezmailing/text')}</span>
						{/if}
					</a>
				</li> 
				<li id="hardbounce">
					<a href={"mailing/registrations/hardbounce"|ezurl}>
						{if and(is_set($subaction),$subaction|eq('hardbounce'))}
							<img    src={"pictos/hard_bounce_state_on.png"|ezimage()} 
									width="55" 
									height="55" 
									alt="{"Hard bounce"|i18n('extension/ezmailing/text')}"
									title="{"Hard bounce"|i18n('extension/ezmailing/text')}" />
							<span>{"Hard bounce"|i18n('extension/ezmailing/text')}</span>
						{else}
							<img    src={"pictos/hard_bounce_state_off.png"|ezimage()} 
									width="55" 
									height="55" 
									alt="{"Hard bounce"|i18n('extension/ezmailing/text')}"
									alt="{"Hard bounce"|i18n('extension/ezmailing/text')}" />
							<span class="off">{"Hard bounce"|i18n('extension/ezmailing/text')}</span>
						{/if}
					</a>
				</li>
			</ul>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>
		<div id="ezmailing_search_form">
			<form   method="post" 
					name="campaignlistfeatures" 
					id="campaignlistfeatures"
					class="jqTransform">
				<div id="ezmailing_sort">
					<h3>{"Order by"|i18n('extension/ezmailing/text')}</h3>
					<select name="order_field" 
							id="order_field" 
							info="{'Please select order field'|i18n( 'extension/ezmailing/text' )}"
							class="jqTransformField customCss">
						<option value="name"
								dir="asc"
								{if $view_parameters.order_field|eq("name")}
									selected="selected"
								{/if}>
							{'REGISTRATION NAME'|i18n( 'extension/ezmailing/text' )}
						</option>
						<option value="mailing_list"
								dir="asc"
								{if $view_parameters.order_field|eq("mailing_list")}
									selected="selected"
								{/if}>
							{'MAILING LIST'|i18n( 'extension/ezmailing/text' )}
						</option>
						<option value="registred"
								dir="desc"
								{if $view_parameters.order_field|eq("registred")}
									selected="selected"
								{/if}>
							{'REGISTRED'|i18n( 'extension/ezmailing/text' )}
						</option>
						<option value="state_updated"
								dir="desc"
								{if $view_parameters.order_field|eq("state_updated")}
									selected="selected"
								{/if}>
							{'LAST STATE CHANGED'|i18n( 'extension/ezmailing/text' )}
						</option>
					</select>
				</div>
				<div id="ezmailing_search">
					<h3>{"Search"|i18n('extension/ezmailing/text')}</h3>
					<p>
						<input  type="text" 
								{if is_set($searched_text)}
									value="{$searched_text}" 
								{else}
									value="{'SEARCH'|i18n( 'extension/ezmailing/text' )}" 
								{/if}
								alt="{'SEARCH'|i18n( 'extension/ezmailing/text' )}" 
								name="SearchRegistrationText" 
								id="ezmailing_search_text" 
								class="switchValue" />
						<input  type="submit" 
								value="" 
								name="SearchRegistrationButton" 
								id="ezmailing_search_ok" />
					</p>
				</div>
			</form>
		</div>
		<div class="clear"></div>
		{/if}

            <form   {if is_set($action)} action={$action|ezurl} {/if} 
        			method="post" 
        			name="userslistform{if is_set($blockid)}_{$blockid}{/if}"
        			class="jqTransform">
				{if module_params().function_name|ne('dashboard')}
				<div id="ezmailing_record_list">
				{/if}
        			{if is_set($searched_text)}
    				<h2>{$lists|count} {"Results for « %search_text »"|i18n( 'extension/ezmailing/text', '', hash( '%search_text', $searched_text ) )}</h2>
    				{/if}
                <ul>
            	{foreach $lists as $registration sequence array('bglight', 'bgdark') as $seq}
	       			{def 	$user 			= $registration.user
	       					$mailing_list 	= $registration.mailing_list
	       					$state_image 	= $registration.state_string_stand|downcase()|explode(' ')|implode('_')
	       			}
	       			{if module_params().function_name|ne('dashboard')}
                    <li class="ezmailing_list_item ezmailing_{$state_image}_registration">
                        <div class="ezmailing_user_email">
	                        <h3>
	                            <a href={$user.url|ezurl}>{$user.first_name|wash} {$user.last_name|wash}</a>
	                        </h3>
	                        <h4>{$user.email|wash}&nbsp;</h4>
                        </div>
                        <div class="ezmailing_mailing_list">
                        	<p class="registration_date">
                        		<a href="#" title="{'Registration date'|i18n( 'extension/ezmailing/text' )}">
	                                <img    src={"pictos/clock.png"|ezimage()} 
	                                        width="23" 
	                                        height="22"  
	                                        alt="{'Registration date'|i18n( 'extension/ezmailing/text' )}" />
	                            </a>
	                            <span class="ezmailing_tooltip">
	                                <span>{'Updated'|i18n( 'extension/ezmailing/text' )} {$registration.state_updated|l10n( 'shortdatetime' )}</span>
	                            </span>
                        		<strong>{'Registred'|i18n( 'extension/ezmailing/text' )} : </strong> {$registration.registred|l10n( 'shortdatetime' )}
                    		</p>
                    		<div class="clear"></div>

							<div class="ezmailing_mailing_list_item">
								<img 	src="{$mailing_list.lang|flag_icon}" 
										width="18" 
										height="12" 
										alt="{$mailing_list.lang}"
										title="{$mailing_list.lang}" />

								<p>
									<a href={$mailing_list.url|ezurl} title="{$mailing_list.name|wash}">{$mailing_list.name|wash}</a>
								</p>
							</div>
                        </div>
                        <div class="ezmailing_state{if $show_registration_content|not()} ezmailing_state_view_mailing_list{/if}">
                        	<img    src={concat("pictos/",$state_image,".png")|ezimage()} 
                                    alt="{$registration.state_string}"
                                    title="{$registration.state_string}"
                                    width="66" height="66" />
                            {if $show_registration_content}
                        	<p>{$registration.state_string}</p>
                        	{/if}
                        </div>
						{if $show_edit}
                        <div class="ezmailing_checkbox_button">
                            <table cellpadding="0" cellspacing="0">
                                <tr>
                                    <td>
                                        <input  type="checkbox" 
                                                name="itemsActionCheckbox[]" 
                                                value="{$registration.mailinglist_id}:{$registration.mailing_user_id}" 
                                                class="jqTransformField" />
                                    </td>
                                </tr>
                            </table>
                        </div>
                        {/if}
                        <div class="clear"></div>
                    </li>
                    {else}
                    <li class="ezmailing_list_item">
                    	<div class="ezmailing_user_email">
	                        <h3>
	                            <a href={$user.url|ezurl}>{$user.first_name|wash} {$user.last_name|wash}</a>
	                        </h3>
	                        <h4>{$user.email|wash}&nbsp;</h4>
                        </div>
                        <div class="ezmailing_mailing_list">
                    		<p>
                    			<a href="#" title="{'Registration date'|i18n( 'extension/ezmailing/text' )}">
	                                <img    src={"pictos/clock.png"|ezimage()} 
	                                        width="23" 
	                                        height="22"  
	                                        alt="{'Registration date'|i18n( 'extension/ezmailing/text' )}" />
	                            </a>
	                            <span class="ezmailing_tooltip">
	                            	<span>{'Registred'|i18n( 'extension/ezmailing/text' )} {$registration.registred|l10n( 'shortdatetime' )}</span>
	                                <span>{'Updated'|i18n( 'extension/ezmailing/text' )} {$registration.state_updated|l10n( 'shortdatetime' )}</span>
	                            </span>
                            </p>
                            <p>
                            	<a href="#" title="{'Mailing list'|i18n( 'extension/ezmailing/text' )}">
	                            	<img    src={"bg/bg_mailing_list.png"|ezimage()} 
	                                        width="23" 
	                                        height="23"  
	                                        alt="{'Mailing list'|i18n( 'extension/ezmailing/text' )}" />
	                            </a>
	                            <span class="ezmailing_tooltip">
	                            	<span>
	                            		<a href={$mailing_list.url|ezurl} title="{$mailing_list.name|wash}">{$mailing_list.name|wash}</a>
	                            		<img 	src="{$mailing_list.lang|flag_icon}" 
											width="18" 
											height="12" 
											alt="{$mailing_list.lang}"
											title="{$mailing_list.lang}" />
	                            		<span class="clear"></span>
	                        		</span>
	                            </span>
                            </p>
                        </div>
                        <div class="clear"></div>
                    </li>
                    {/if}
                    {undef $user $mailing_list $state_image}
       			{/foreach}
                </ul>
                <div class="clear"></div>
            {if module_params().function_name|ne('dashboard')}         
        	</div>
        	{/if}
        	{if or( $show_search_form, $show_edit )}				
                {def $lists_count_b = 0}
                {if or( and( is_set( $embed ), $embed|not() ), is_unset( $embed ) )}
	                {def
	                	$page_limit_b 	= ezini('PaginationSettings','RegistrationsLimit','ezmailing.ini')
	        			$page_uri_b 		= concat( '/mailing/registrations', cond( $subaction|ne(''), concat('/', $subaction),true(),'' ),
	        																cond( is_set($searched_text), concat( '/', $searched_text ), true(), '' ) )
	                }
	                {set $lists_count_b 	= fetch('mailing','fetch_count',hash(
	                                                       'type','registrations',
	                                                       'filter',cond( is_set($state_filter), hash( 'state',$state_filter ), is_set($filter), $filter, true(), hash() )
	                                                   ))
					}
	                {include name='navigator'
	                     uri='design:navigator/google.tpl'
	                     page_uri=$page_uri_b
	                     item_count=$lists_count_b
	                     view_parameters=$view_parameters
	                     item_limit=$page_limit_b}
	            	{undef $lists_count_b $page_limit_b $page_uri_b}
	            {/if}
	            {if and( is_set( $edit ), $edit, $lists|count|gt(0) )}
                <div id="ezmailing_actions_submit">
					<ul>
                        <li id="remove_selected">
                            <button     type="submit" 
                                        name="RemoveRegistrationsButton" 
                                        title="{'Remove selected'|i18n( 'extension/ezmailing/text' )}"
                                        disabled="disabled">
                                {'Remove'|i18n( 'extension/ezmailing/text' )}<br />{'selected'|i18n( 'extension/ezmailing/text' )}
                            </button>
                        </li>                        
                        <li id="export_campaign">
                            <a href={concat(  	"mailing/export/Registration/", 
						                        cond(   is_set( $state_filter ), $state_filter, 
						                                is_set( $searched_text ), concat('search/', $searched_text),
						                                true(), '' 
						                        ),
						                        cond( is_set( $item ), $item.id, '' ),
						                        cond( is_set( $item ), "/", '' ),
						                        cond( is_set( $item ), $item.name, '' ),
						                        cond( is_set( $item ), "/(fix_item_type)/", '' ),
						                        cond( is_set( $item ), "MailingList/", '' ),
						                        cond( is_set( $item ), "(fix_item_id)/", '' ),
						                        cond( is_set( $item ), $item.id, '' )
				                )|ezurl} title="{'CSV export'|i18n( 'extension/ezmailing/text' )}"{if and( is_set( $item ), $item.registrations_count|eq(0) )} onclick="return false;"{/if}>
                                {'Export All'|i18n( 'extension/ezmailing/text' )}
                            </a>
                        </li>                        
                    </ul>
                    <div class="clear"></div>
                </div>
                {/if}
                <div class="clear"></div>
            </div>
            {/if}
        </form>
{if $show_registration_content}
    </div>
</div>
{/if}
{undef $show_registration_content $show_edit}
