{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="ezmailing_container" class="ezmailing_users_container">
    <div id="ezmailing_content">
        <h2>{"Users list"|i18n('extension/ezmailing/text')}</h2>
        <div id="ezmailing_item_states">        
            <h3>{"Show only users with this selected state :"|i18n('extension/ezmailing/text')}</h3>
            <ul>
                <li id="listed">
                    <a  href={"mailing/users"|ezurl} 
                        alt="{"LISTE"|i18n('extension/ezmailing/text')}">
                        {if is_set($subaction)|not()}
                            <img    src={"pictos/listed_state_on.png"|ezimage()} 
                                    width="55" 
                                    height="55" 
                                    alt="{"LISTE"|i18n('extension/ezmailing/text')}" />
                            <span>{"LISTE"|i18n('extension/ezmailing/text')}</span>
                        {else}
                            <img    src={"pictos/listed_state_off.png"|ezimage()} 
                                    width="55" 
                                    height="55" 
                                    alt="{"LISTE"|i18n('extension/ezmailing/text')}" />
                            <span class="off">{"LISTE"|i18n('extension/ezmailing/text')}</span>
                        {/if}
                    </a>
                </li>
                <li id="orphan">
                    <a href={"mailing/users/orphan"|ezurl}>
                        {if and(is_set($subaction),$subaction|eq('orphan'))}
                            <img    src={"pictos/orphan_state_on.png"|ezimage()} 
                                    width="55" 
                                    height="55" 
                                    alt="{"Orphan"|i18n('extension/ezmailing/text')}" />
                            <span>{"Orphan"|i18n('extension/ezmailing/text')}</span>
                        {else}
                            <img    src={"pictos/orphan_state_off.png"|ezimage()} 
                                    width="55" 
                                    height="55" 
                                    alt="{"Orphan"|i18n('extension/ezmailing/text')}" />
                            <span class="off">{"Orphan"|i18n('extension/ezmailing/text')}</span>
                        {/if}
                    </a>
                </li>
            </ul>
            <div class="clear"></div>
        </div>
        <div id="ezmailing_search_form">
		    <form   method="post" 
		            name="campaignlistfeatures" 
		            id="campaignlistfeatures"
		            class="jqTransform">
		        <div id="ezmailing_sort">
		        	<h3>{"Order by"|i18n('extension/ezmailing/text')}</h3>
		            <select name="order_field" 
		                    id="order_field" 
		                    info="{'Please select order field'|i18n( 'extension/ezmailing/text' )}"
		                    class="jqTransformField customCss">
		                <option value="name"
		                        dir="asc"
		                        {if $view_parameters.order_field|eq("name")}
		                            selected="selected"
		                        {/if}>
		                    {'EMAIL'|i18n( 'extension/ezmailing/text' )}
		                </option>
		                <option value="registred"
		                        dir="desc"
		                        {if $view_parameters.order_field|eq("registred")}
		                            selected="selected"
		                        {/if}>
		                    {'REGISTRED'|i18n( 'extension/ezmailing/text' )}
		                </option>
		            </select>
		        </div>
		        <div id="ezmailing_search">
		        	<h3>{"Search"|i18n('extension/ezmailing/text')}</h3>
		            <p>
		                <input  type="text" 
		                        {if is_set($searched_text)}
		                            value="{$searched_text}" 
		                        {else}
		                            value="{'SEARCH'|i18n( 'extension/ezmailing/text' )}" 
		                        {/if}
		                        alt="{'SEARCH'|i18n( 'extension/ezmailing/text' )}" 
		                        name="SearchUserText" 
		                        id="ezmailing_search_text" 
		                        class="switchValue" />
		                <input  type="submit" 
		                        value="" 
		                        name="SearchUserButton" 
		                        id="ezmailing_search_ok" />
		            </p>
		        </div>
		    </form>
		</div>
		<div class="clear"></div>
		<div id="ezmailing_record_list">
            <form   {if is_set($action)} action={$action|ezurl} {/if} 
        			method="post" 
        			name="userslistform{if is_set($blockid)}_{$blockid}{/if}"
        			class="jqTransform">
        		{if is_set($searched_text)}<h2>{$lists_count_b} {"Results for « %search_text »"|i18n( 'extension/ezmailing/text', '', hash( '%search_text', $searched_text ) )}</h2>{/if}
                <ul>
            	{foreach $lists as $item sequence array('bglight', 'bgdark') as $seq}
	       			{def
                       $registrationsSummary = $item.registrationsSummary
                       $registrationsCount = $item.registrations|count
                       }
                    <li class="ezmailing_list_item ezmailing_{if and(is_set($subaction),$subaction|eq('orphan'))}orphan{/if}_user">
                        <p class="ezmailing_sending_date">
                            <strong>{'Registred'|i18n( 'extension/ezmailing/text' )} : </strong> {$item.registred|l10n( 'shortdatetime' )}
                            <a href="#" title="{'Sending Date'|i18n( 'extension/ezmailing/text' )}">
                                <img    src={"pictos/clock.png"|ezimage()} 
                                        width="23" 
                                        height="22"  
                                        alt="{'Sending Date'|i18n( 'extension/ezmailing/text' )}" />
                            </a>
                            <span class="ezmailing_tooltip">
                                <span>{'Updated'|i18n( 'extension/ezmailing/text' )} {$item.updated|l10n( 'shortdatetime' )}</span>
                            </span>
                        </p>
                        <div class="clear"></div>
                        <div class="ezmailing_user_email">
	                        <h3>
	                            <a href={$item.url|ezurl}>{$item.first_name|wash} {$item.last_name|wash}</a>
	                        </h3>
	                        <h4>{$item.email}&nbsp;</h4>
                        </div>
                        <div class="ezmailing_mailing_list">
                        	{if and(
                                    or( is_set( $orphanMode )|not, $orphanMode|eq(false())),
                                    $registrationsCount|gt(0)
                            )}
                                <h5>{"Registration states"|i18n('extension/ezmailing/text')}</h5>
	                            {foreach $registrationsSummary as $registrationSummary}
										<div class="ezmailing_mailing_list_item">
											<p>
												{$registrationSummary.state|wash} ({$registrationSummary.count|wash})
											</p>
										</div>
	                                   {undef $mailing_list}
			                   {/foreach}
		                   {/if}
                        </div>
                        <div class="ezmailing_state">
                            {if $registrationsCount|gt(0)}
                                <img    src={"pictos/listed_user.png"|ezimage()}
                                                width="66"
                                height="66"
                                alt="{"LISTE"|i18n('extension/ezmailing/text')}" />
                                <p>{"LISTE"|i18n('extension/ezmailing/text')}</p>
                                {else}
                                <img    src={"pictos/orphan_user.png"|ezimage()}
                                                width="66"
                                height="66"
                                alt="{"Orphan"|i18n('extension/ezmailing/text')}" />
                                <p>{"Orphan"|i18n('extension/ezmailing/text')}</p>
                            {/if}
                        </div>

                        <div class="ezmailing_open_actions">
                            <a href="#">
                                <span>{'Actions'|i18n( 'extension/ezmailing/text' )}</span>
                                <img    src={"pictos/actions_down_arrow.png"|ezimage()} 
                                        width="44" 
                                        height="45" 
                                        alt="Actions" />
                            </a>
                        </div>
                        <div class="ezmailing_checkbox_button">
                            <table cellpadding="0" cellspacing="0">
                                <tr>
                                    <td>
                                        <input  type="checkbox" 
                                                name="itemsActionCheckbox[]" 
                                                value="{$item.id}" 
                                                class="jqTransformField" />
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="ezmailing_actions_buttons">
                            <ul>
                                <li class="edit_record">
                                    <a href={concat( '/mailing/users/edit/', $item.id )|ezurl} title="{'Edit %user_name.'|i18n( 'extension/ezmailing/text',, hash( '%user_name', $item.name ) )|wash}">{'Edit'|i18n( 'extension/ezmailing/text' )}</a>
                                </li>
                                <li class="remove_record">
                                    <a href={concat( '/mailing/users/delete/', $item.id )|ezurl} title="{'Remove %user_name.'|i18n( 'extension/ezmailing/text',, hash( '%user_name', $item.name ) )|wash}">{'Remove'|i18n( 'extension/ezmailing/text' )}</a>
                                </li>
                            </ul>
                            <div class="ezmailing_close_actions">
                                <a href="#">
                                    <span>{'Close'|i18n( 'extension/ezmailing/text' )}</span>
                                    <img src={"pictos/actions_up_arrow.png"|ezimage()} width="44" height="45" alt="FERMER" />
                                </a>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </li>
                    {undef $registrationsSummary $registrationsCount}
       			{/foreach}
                </ul>

                {include name='navigator'
                     uri='design:navigator/google.tpl'
                     page_uri=$page_uri_b
                     item_count=$lists_count_b
                     view_parameters=$view_parameters
                     item_limit=$page_limit_b}

                <div id="ezmailing_actions_submit">
					<ul>
                        <li id="remove_selected">
                            <button     type="submit" 
                                        name="RemoveUsersButton" 
                                        title="{'Remove selected users.'|i18n( 'extension/ezmailing/text' )}"
                                        disabled="disabled">
                                {'Remove'|i18n( 'extension/ezmailing/text' )}<br />{'selected'|i18n( 'extension/ezmailing/text' )}
                            </button>
                        </li>
                        <li id="new_record">
                            <button     type="submit" 
                                        name="CreateUserButton" 
                                        title="{'Create a user.'|i18n( 'extension/ezmailing/text' )}">
                                {'Create new user'|i18n( 'extension/ezmailing/text' )}
                            </button>
                        </li>
                        {if $lists|count|gt(0)}
                            <li id="export_campaign">
                                <a href={concat(   "mailing/export/User/",
                                            cond(   is_set( $fetchkey ), $fetchkey,
                                                    is_set( $search_text ), concat('search/', $search_text),
                                                    true(), ''
                                            )
                                    )|ezurl} title="{'CSV export'|i18n( 'extension/ezmailing/text' )}">
                                    {'Export All'|i18n( 'extension/ezmailing/text' )}
                                </a>
                            </li>
                        {/if}
                    </ul>
                    <div class="clear"></div>
                </div>
                <div class="clear"></div>
            </form>
        </div>
    </div>
</div>   