{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{include uri="design:mailing/common/header.tpl" page="search"}

{def $filter = array()}
{foreach $search_fields as $search_field}
    {set $filter =  $filter|merge(  hash(   $search_field, 
                                            array(
                                                'like', 
                                                concat('%', $search_text, '%')
                                            )
                                    )   )}
{/foreach}
{set    $filter = hash( 'or', $filter)}

{def
    $page_limit_b = ezini('PaginationSettings','UsersLimit','ezmailing.ini')
    $lists          =   fetch(  'mailing', 'fetch',     hash(
                                                            'type', 'users',
                                                            'filter', $filter,
                                                            'limit', $page_limit_b,
                                                            'offset', $view_parameters.offset,
                                                            'sort_by', $sort_by
                                                        )
                        )

    $page_uri_b = concat( '/mailing/users', 	cond( $subaction|ne(''), concat('/', $subaction),true(),'' ),
                                                cond( is_set($search_text), concat( '/', $search_text ), true(), '' ) )

    $lists_count_b = fetch('mailing','fetch_count',hash(
                                    'type', cond( $orphanMode, 'orphanusers', true(), 'users' ),
                                    'filter',cond( is_set($state_filter), hash( 'state',$state_filter), is_set($filter), $filter, true(), hash() )
                                    )
                         )
}
    {include
            uri="design:mailing/list/users.tpl"
            lists=$lists
            searched_text=$search_text|wash
            lists_count_b=$lists_count_b
            page_limit_b=$page_limit_b
            page_uri_b=$page_uri_b
    }

{undef $lists  $page_limit_b $filter $page_uri_b $lists_count_b}

{include uri="design:mailing/common/footer.tpl"}