{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{include uri="design:mailing/common/header.tpl" page='view'}
<div id="ezmailing_container">
	<div id="ezmailing_content">
		<h2>{'User'|i18n( 'extension/ezmailing/text' )}</h2>
		<div id="ezmailing_edit" class="ezmailing_view_user">
			<div id="user_main_information" class="inlineBlock">
				<h3>{$item.first_name|wash} {$item.last_name|wash}</h3>
				<h4>{$item.email|wash}</h4>
				{if is_set($item.ezuser.contentobject)}
				<p>
					<strong>{'eZ publish account'|i18n( 'extension/ezmailing/text' )}</strong><a href={$item.ezuser.contentobject.main_node.url_alias|ezurl}>{$item.ezuser.contentobject.name}</a>
				</p>
				{/if}
			</div>
			{def 	$attributes 		= ezini( 'MailingUserAccountSettings', 'Attributes', 'ezmailing.ini' )
					$block				= 0
					$templateAttribute 	= false()}
            {foreach $attributes as $identifier => $label}
            	{set $templateAttribute = concat( 'design:mailing/users/attributes/', $identifier, '.tpl' )}
            	{if or( $block|eq( 3 ), $block|eq( 6 ) )}
            		</div>
            	{/if}
            	{if $block|eq( 6 )}
            			<div class="clear"></div>
            		</div>
            	{/if}
            	{if or( $block|eq( 0 ), $block|eq( 6 ) )}
            		<div class="inlineBlock">
            		{set $block = 0}
            	{/if}
            	{if or( $block|eq( 3 ), $block|eq( 0 ) )}
            		<div class="ezmailing_edit_{cond( $block|eq( 0 ), 'left', true(), 'right' )}">
            	{/if}
            	
                {include uri=$templateAttribute}
                
                {set $block = $block|inc()}
            {/foreach}
            {if $attributes|count}
            	</div>
            	<div class="clear"></div>
            </div>
            {/if}
			<div id="user_registrations" class="inlineBlock">
				<h3>{'Registration'|i18n( 'extension/ezmailing/text' )}</h3>
				<div id="ezmailing_record_list">			
					{def $mapping = $item.all_mailing_lists_with_registrations}
					<ul>
					{foreach $mapping as $map sequence array('bglight', 'bgdark') as $seq}
						{def 
    						$mailingList = $map.mailing
    						$registration = $map.registration
						}
                        {if $registration}
                            <li class="ezmailing_list_item">
                                <div class="registration_description">
                                    {if $registration.mailinglist_id}
                                    <p>{'Registration date'|i18n( 'extension/ezmailing/text' )} : <span>{$registration.state_updated|l10n( 'shortdatetime' )}</span></p>
                                    {/if}
                                    <div class="clear"></div>
                                    <img src="{$mailingList.lang|flag_icon}" width="18" height="12" alt="{$mailingList.lang}" title="{$mailingList.lang}" />
                                    <p class="mailing_list_name">
                                        <a href={$mailingList.url|ezurl}>{$mailingList.name|wash}</a>
                                    </p>
                                    <div class="clear"></div>
                                </div>
                                <div class="registration_status {$registration.state_string|downcase()}">
                                {if $registration.state_string|downcase()|eq('registred')}
                                    <img src={"pictos/registred_user.png"|ezimage} alt="Registred" width="70" height="70" />
                                {elseif $registration.state_string|downcase()|eq('unregistred')}
                                    <img src={"pictos/unregistred_user.png"|ezimage} alt="Unregistred" width="70" height="70" />
                                {/if}
                                    <p>{$registration.state_string}</p>
                                </div>
                                <div class="clear"></div>
                            </li>
                        {/if}
						{undef $mailingList $registration}
					{/foreach}
					</ul>  
			        {undef $mapping}
				</div>		
			</div>
		</div>
	</div>
</div>
<form method="post" action={concat( '/mailing/users/edit/', $item.id )|ezurl}>
	<span id="edit_record">
		<button type="submit" title="{'Edit this user.'|i18n( 'extension/ezmailing/text' )}">{'Edit'|i18n( 'extension/ezmailing/text' )}</button>
	</span>    
</form>
{include uri="design:mailing/common/footer.tpl"}