{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="ezmailing_header" class="mailing_lists_header">
	<h1>{$title}</h1>
	<p id="ezmailing_header_text">
        {"Edit name and language of the mailing list. You can also delete registrations entries."|i18n( 'extension/ezmailing/text' )}
    </p>
	<div class="clear"></div>
</div>