{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="ezmailing_header" class="mailing_lists_header">
	<form {if is_set($action)} action={$action|ezurl} {/if} method="post" name="campaignlistform{if is_set($blockid)}_{$blockid}{/if}">
        <h1>{$title}</h1>
        <input type="submit" name="CreateMailingListButton" title="{"Create new mailing list"|i18n( 'extension/ezmailing/text' )}" value="{"Create a mailing list"|i18n( 'extension/ezmailing/text' )}" />
        <p id="ezmailing_header_text">
        	{"Mailing lists available to send new campaign."|i18n( 'extension/ezmailing/text' )}
        </p>
    </form>
	<div class="clear"></div>
</div>