{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="ezmailing_header" class="mailing_lists_header view">
    <form {if is_set($action)} action={$action|ezurl} {/if} method="post" name="campaignlistform{if is_set($blockid)}_{$blockid}{/if}">
        <div id="ezmailing_header_status">
            <input class="button" type="submit" name="CreateMailingListButton" title="{"Create new mailing lists"|i18n( 'extension/ezmailing/text' )}" value="{"Create a mailing list"|i18n( 'extension/ezmailing/text' )}" />
        </div>
        <h1>{$title}</h1>
        <p id="ezmailing_header_text">
        	{"Information about the mailing list %mailinglist_name. You can edit or export registrations entries."|i18n( 'extension/ezmailing/text', , hash( '%mailinglist_name', $path.1.text|wash ) )}
        </p>
        <div class="clear"></div>
        <div id="ezmailing_header_details">
            <div id="left_details">
                <p>
                	<strong>{"Id"|i18n('extension/ezmailing/text')}</strong> : {$item.id}
                </p>
                {if $item|is_provided}
                <p>
                    <strong>{"Remote number of registrations"|i18n( 'extension/ezmailing/text' )} : </strong>
                    {cond($item.remote_id|ne(''), $item.count_remote_registration, 'NA')}
                </p>
                {/if}
            </div>
            <div id="right_details">
                <p>
                	<strong>{"Created"|i18n( 'extension/ezmailing/text' )}</strong> : {$item.created|l10n( 'shortdatetime' )}
                </p>
                <p>
                	<strong>{"Updated"|i18n( 'extension/ezmailing/text' )}</strong> : {$item.updated|l10n( 'shortdatetime' )}
                </p>
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
        <div id="grabber">
            <a href="#" title="{"AFFICHER/CACHER DETAILS"|i18n( 'extension/ezmailing/text' )}">
            	<img src={"pictos/grabber.png"|ezimage()} width="38" height="15" />
            </a>
        </div>
    </form>
    <div class="clear"></div>
</div>