{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{include uri="design:mailing/common/header.tpl" page='edit'}

<form method="post" action={concat( '/mailing/mailinglists/edit/', $item.id )|ezurl} class="jqTransform">
	<div id="ezmailing_container">
		<div id="ezmailing_content">
			<h2>{'Edit list'|i18n( 'extension/ezmailing/text' )}</h2>
			<div id="ezmailing_edit" class="ezmailing_edit_list">
				<div class="inlineBlock">
					<div class="ezmailing_edit_left">
						<div class="block">
							<label for="name">{'Name'|i18n( 'extension/ezmailing/text' )}<span class="required">*</span></label>
			    			<input type="text" id="name" name="name" value="{$item.name|wash}" />
			    			<div class="clear"></div>
		    			</div>
                        {if $item.draft|eq(0)}
		    			<div class="block">
							<label for="id">{'ID'|i18n( 'extension/ezmailing/text' )}</label>
			    			<p>{$item.id|wash}<p/>
			    			<div class="clear"></div>
		    			</div>
                        {/if}
					</div>
					<div class="ezmailing_edit_right">
						<div class="block">
							<label for="lang">{'Language'|i18n( 'extension/ezmailing/text' )}<span class="required">*</span></label>
				        	<select id="lang" name="lang" class="jqTransformField customCss customCss2">
					            {foreach $available_translations as $trans}
					                <option value="{$trans.locale_object.locale_code}" {if $trans.locale_object.locale_code|eq($item.lang)} selected="selected" {/if}>{$trans.name|wash}</option>
					            {/foreach}
					        </select>
					        <div class="clear"></div>
		    			</div>
                        {if $item.draft|eq(0)}
		    			<div class="block">
							<label for="id">{'Created'|i18n( 'extension/ezmailing/text' )}</label>
			    			<p>{$item.created|l10n( 'shortdatetime' )}<p/>
			    			<div class="clear"></div>
		    			</div>
		    			<div class="block">
							<label for="id">{'Updated'|i18n( 'extension/ezmailing/text' )}</label>
			    			<p>{$item.updated|l10n( 'shortdatetime' )}<p/>
			    			<div class="clear"></div>
		    			</div>
                        {/if}
					</div>
					<div class="clear"></div>
					<span id="store_record">
						<button type="submit" name="StoreMailingButton" title="{'Store user'|i18n( 'extension/ezmailing/text' )}">{'Store'|i18n( 'extension/ezmailing/text' )}</button>
					</span>	
				</div>
			</div>			
		</div>
	</div>
</form>

{if $view_parameters.order_field}
    {def 
        $page_limit = ezini('PaginationSettings','RegistrationsLimit','ezmailing.ini')
        $lists_count = fetch('mailing','fetch_count',hash(
                                                       'type','registrations',
                                                       'filter', hash( 'mailinglist_id', $item.id ),
                                                   )
                              )
        $lists = fetch('mailing','fetch',hash(
                                                       'type','registrations',
                                                       'filter',hash( 'mailinglist_id', $item.id ),
                                                       'sort_by', hash( $view_parameters.order_field, $view_parameters.order_dir )
                                                   )
                              )
    }
{elseif is_unset($lists)}
    {def $lists = $item.registrations}
{/if}



<div id="mailing_lists_registrations" class="mailing_lists_registrations_edit">
	<h3>{'Registrations in this mailing list (%number_of_users)'|i18n( 'extension/ezmailing/text',, hash( '%number_of_users', $lists|count ) )}</h3>
	{include uri="design:mailing/list/registrations.tpl" lists=$lists edit=true()  embed=true()}
</div>

{undef $lists}

{include uri="design:mailing/common/footer.tpl"}