{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{include uri="design:mailing/common/header.tpl" page='list'}
    {if is_unset($sort_by)}
        {def $sort_by = hash( 'created', 'desc')}
    {/if}
    
    {def $lists = fetch('mailing','fetch',hash(
                                                       'type','mailinglist',
                                                       'sort_by', $sort_by
                                                   )
                              )
    }
         {include uri="design:mailing/list/mailinglists.tpl" lists=$lists}
	{undef $lists}
{include uri="design:mailing/common/footer.tpl"}