{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{include uri="design:mailing/common/header.tpl" page="search"}
    {if is_unset($sort_by)}
        {def $sort_by = hash( 'created', 'desc')}
    {/if}
    {def $results   =   fetch(  'mailing','fetch',  hash(
                                                        'type', 'mailinglist',
                                                        'filter',   hash(
                                                                        'name', 
                                                                        array(
                                                                            'like', 
                                                                            concat('%', $search_text, '%')
                                                                        ) 
                                                                    ), 
                                                        'sort_by', $sort_by
                                                    )
                        )}
    {include uri="design:mailing/list/mailinglists.tpl" lists=$results searched_text=$search_text|wash}
{include uri="design:mailing/common/footer.tpl"}