{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{include uri="design:mailing/common/header.tpl" page='view'}
{def $itemId=$item.id}
<div id="ezmailing_container" class="mailing_lists_edit_container">
	<div id="ezmailing_content">
		<div id="mailinglist_view_title">
			<h2>{$item.name|wash}<span><img src="{$item.lang|flag_icon}" width="18" height="12" alt="{$item.lang}" />{$item.lang}</span></h2>
		</div>
	</div>
</div>

{if $item.is_available}
    {if $item|is_provided}
        {def $uptodate = and( $item.remote_id|ne(''), $item.count_remote_registration|eq( $item.registrations_count ) )}

                <br />
                {if $uptodate}
                <div class="message-feedback">
                    <h2>{"The mailing list is up-to-date with the remote mailing list."|i18n( 'extension/ezmailing/text' )}</h2>
                </div>
                {elseif $item.remote_id|ne('')}
                <div class="message-warning">
                    <h2>{"There are currently %number_of_users local registrations versus %number_of_remote remote ones, do you want to synchronize the mailing list?"|i18n( 'extension/ezmailing/text',, hash( '%number_of_users', $item.registrations_count, '%number_of_remote', $item.count_remote_registration ))}</h2>
                </div>
                {else}
                <div class="message-warning">
                    <h2>{"The mailing list is still not synchronized."|i18n( 'extension/ezmailing/text' )}</h2>
                </div>
                {/if}
                <br />
                <form method="post" action={concat( '/mailing/mailinglists/view/', $item.id )|ezurl}>
                    <input {if $uptodate}class="button-disabled" disabled="disabled"{else}class="button"{/if} type="submit" name="SynchronizeRegistrationsButton" value="{'Synchronize'|i18n( 'extension/ezmailing/text' )}" title="{'Synchronize'|i18n( 'extension/ezmailing/text' )}" />
                </form>

        {undef $uptodate}
    {/if}
{else}
    {if $item.is_importing}
    <div class="message-feedback">
        <h2>{"An import is currently running on the mailing list."|i18n( 'extension/ezmailing/text' )}</h2>
    </div>
    {/if}
    {if $item.is_synchronizing}
    <div class="message-feedback">
        <h2>{"A synchronisazion is currently running on the mailing list."|i18n( 'extension/ezmailing/text' )}</h2>
    </div>
    {/if}
{/if}

{def
    $lists = $item.last_registrations
}
<div id="mailing_lists_registrations">
	<h3>{'Last registrations in this mailing list (%number_of_users)'|i18n( 'extension/ezmailing/text',, hash( '%number_of_users', $item.registrations_count ) )}</h3>
	{include uri="design:mailing/list/registrations.tpl" lists=$lists edit=false()  embed=true()}
</div>
<form method="post" action={concat( '/mailing/mailinglists/edit/', $itemId )|ezurl}>
    <div id="registrations_actions_submit"{if is_set($show_registration_content)} class="registrations_actions_submit"{/if}>
		<ul>
			
            <li id="edit_mailing_lists">
                <button     type="submit" 
                            title="{'Edit this mailing list.'|i18n( 'extension/ezmailing/text' )}">
                    {'Edit'|i18n( 'extension/ezmailing/text' )}
                </button>
            </li>
            <li id="registrations_export">
                <a href={concat( "/mailing/export/Registration/(fix_item_type)/MailingList/(fix_item_id)/", $item.id )|ezurl} title="{'CSV e xport'|i18n( 'extension/ezmailing/text' )}">
                    {'Export All'|i18n( 'extension/ezmailing/text' )}
                </a>
            </li>
            <li id="remove_mailinglist">
                <a href={concat("mailing/mailinglists/delete/", $itemId)|ezurl()}>
                {'Remove'|i18n( 'extension/ezmailing/text' )}
                </a>
            </li>
        </ul>
        <div class="clear"></div>
    </div>
</form>
{undef $itemId}
{include uri="design:mailing/common/footer.tpl"}