{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{include uri="design:mailing/common/header.tpl" page='send'}

{def 	$url 		= $item.campaign_url
		$resend 	= $item.resend_actions
		$isScheduled  = $item.scheduled}

<form method="post" action={concat( '/mailing/campaigns/send/', $item.id )|ezurl}>
	<div id="ezmailing_container">
		<div id="ezmailing_content">
			<h2>{'Send campaign'|i18n( 'extension/ezmailing/text' )}</h2>
			<div class="sending_compaign">
				<div class="sending_compaign_steps">
					{def $step=''}
					<table cellpadding="0" cellspacing="0">
						<tr>
							<td class="send_test">
								{if and( $item.is_draft_succeed, $item.is_cancelled|not(), $item.is_deleted|not() )}
									{set $step='pictos/steps/step_1_2.png'}
								{else}
									{set $step='pictos/steps/step_1_1.png'}
								{/if}
								<img src={$step|ezimage()} width="144" height="65" alt="" />
							</td>
							<td>
								{if and( $item.is_tested_succeed, $item.is_cancelled|not(), $item.is_deleted|not() )}
									{set $step='pictos/steps/step_2_3.png'}
								{elseif $item.is_tested}
									{set $step='pictos/steps/step_2_2.png'}
								{else}
									{set $step='pictos/steps/step_2_1.png'}
								{/if}
								<img src={$step|ezimage()} width="170" height="65" alt="" />
							</td>
							<td>
								{if and( $item.is_confirmed_succeed, $item.is_cancelled|not(), $item.is_deleted|not() )}
									{set $step='pictos/steps/step_3_3.png'}
								{elseif $item.is_confirmed}
									{set $step='pictos/steps/step_3_2.png'}
								{else}
									{set $step='pictos/steps/step_3_1.png'}
								{/if}
								<img src={$step|ezimage()} width="170" height="65" alt="" />
							</td>
							<td>
								{if and( $item.is_waiting_for_send_succeed, $item.is_cancelled|not(), $item.is_deleted|not() )}
									{set $step='pictos/steps/step_4_3.png'}
								{elseif $item.is_waiting_for_send}
									{set $step='pictos/steps/step_4_2.png'}
								{else}
									{set $step='pictos/steps/step_4_1.png'}
								{/if}
								<img src={$step|ezimage()} width="170" height="65" alt="" />
							</td>
							<td>
								{if $item.is_sent}
									{set $step='pictos/steps/step_5_2.png'}
								{else}
									{set $step='pictos/steps/step_5_1.png'}
								{/if}
								<img src={$step|ezimage()} width="116" height="65" alt="" />
							</td>
						</tr>
						<tr>
							<td class="send_test">
								<div class="{if and( $item.is_draft_succeed, $item.is_cancelled|not(), $item.is_deleted|not() )}on{else}off{/if}">
									<span class="step_number">1</span>
									<p class="text">{'Send campaign to the webmaster'|i18n( 'extension/ezmailing/text' )}</p>
									<input id="SendTestEmail" type="text" name="SendTestEmail" placeholder="email@email.net" title="exemple : email_1@email.net; email_2@email.net" class="switchValue" />
								</div>
							</td>
							<td>
								<div class="{if and( $item.is_tested_succeed, $item.is_cancelled|not(), $item.is_deleted|not() )}on{else}off{/if}">
									<span class="step_number">2</span>
									<p class="text">{'Confirm campaign'|i18n( 'extension/ezmailing/text' )}</p>
								</div>
							</td>
							<td>
								<div class="{if and( $item.is_confirmed_succeed, $item.is_cancelled|not(), $item.is_deleted|not() )}on{else}off{/if}">
									<span class="step_number">3</span>
									<p class="text">{'Validate campaign sending'|i18n( 'extension/ezmailing/text' )}</p>
								</div>	                        	
							</td>
							<td>
								<div class="{if and( $item.is_sending_in_progress_succeed, $item.is_cancelled|not(), $item.is_deleted|not() )}on{else}off{/if}">
									<span class="step_number">4</span>
									<p class="text">{'Sending in progress'|i18n( 'extension/ezmailing/text' )}</p>
								</div>
							</td>
							<td>
								<div class="{if $item.is_sent}on{else}off{/if}">
									<span class="step_number">5</span>
									<p class="text">{'Sending finished'|i18n( 'extension/ezmailing/text' )}</p>
								</div>
							</td>
						</tr>
						<tr class="buttons">
							<td class="send_test">								
								<span {if $item.is_confirmed_succeed}class="button-disabled" {/if}>
	                            	<button {if $item.is_confirmed_succeed} disabled="disabled" class="button-disabled" {else} class="button" {/if} type="submit" name="SendTestButton" title="{'Edit this campaign.'|i18n( 'extension/ezmailing/text' )}" />{'Send for test'|i18n( 'extension/ezmailing/text' )}</button>
	                            </span>
	                            <p>{if $item.is_tested} {$item.state_updated|l10n( 'shortdatetime' )}{/if}</p>
							</td>
							<td>								
								<span {if $item.is_tested|not} class="button-disabled"{/if}>
	                    			<button {if $item.is_tested|not} disabled="disabled" class="button-disabled" {else} class="button" {/if} type="submit" name="ConfirmButton" title="{'Confirm campaign.'|i18n( 'extension/ezmailing/text' )}">{'Confirm'|i18n( 'extension/ezmailing/text' )}</button>
	                        	</span>
	                        	<p>{if $item.is_confirmed} {$item.state_updated|l10n( 'shortdatetime' )}{/if}</p>
							</td>
							<td>
								<span {if $item.is_confirmed|not} class="button-disabled" {/if}>
	                        		<button {if $item.is_confirmed|not} disabled="disabled" class="button-disabled" {else} class="button" {/if} type="submit" name="ValidSendingButton" title="{'Validate this campaign.'|i18n( 'extension/ezmailing/text' )}">{'Validate'|i18n( 'extension/ezmailing/text' )}</button>
	                        	</span>
	                        	<p>{$item.receivers_count} {'Receiver(s)'|i18n( 'extension/ezmailing/text' )}</p>
	                			{if $item.is_waiting_for_send}<p>{$item.state_updated|l10n( 'shortdatetime' )}</p>{/if}
							</td>
							<td>{if $item.is_sending_in_progress}<p>{$item.state_updated|l10n( 'shortdatetime' )}</p>{/if}
							</td>
							<td>{if $item.is_sent}<p>{$item.state_updated|l10n( 'shortdatetime' )}</p>{/if}</td>
						</tr>
                        <tr class="buttons">
                            <td>
                                {if is_provided()}
                                    <span {if or( $item.is_sent|not(), $isScheduled )}class="button-disabled" {/if}>
	                            	<button  class="button" {if or( $item.is_sent|not(), $isScheduled )}disabled="disabled" {/if}type="submit" name="ResendCampagnNoOpenButton"  />{"Re-send"|i18n( 'extension/ezmailing/text' )}</button>
	                            </span>
                                    {if $resend|count|gt( 0 )}
                                        <div class="resend_scheduled">
                                            {if $isScheduled}
                                                <p class="actif">{"Re-sending in progess."|i18n( 'extension/ezmailing/text' )}</p>
                                            {/if}
                                            {foreach $resend as $action}
                                                <p>{"Re-sent %date."|i18n( 'extension/ezmailing/text',, hash( '%date', $action.last_update|l10n( 'shortdatetime' ) ))}</p>
                                            {/foreach}
                                        </div>
                                    {/if}
                                {/if}
                            </td>
                        </tr>
					</table>
					{undef $step}
					<div class="clear"></div>				
				</div>
				<div id="canceling_compaign">
					<h2>{'Cancelling campaign'|i18n( 'extension/ezmailing/text' )}</h2>
					<ul>
						<li id="cancel_compaign">
							<span {if or( and( $item.is_sending_in_progress_succeed, $item.is_cancelled|not(), $item.is_deleted|not() ), $item.is_sending_in_progress, $item.is_editable )} class="button-disabled"{/if}>
								<button type="submit" name="CancelToDraftButton" title="{'Cancel sending of this campaign.'|i18n( 'extension/ezmailing/text' )}"{if or($item.is_sending_in_progress_succeed,$item.is_sending_in_progress)} disabled="disabled" class="button-disabled"{else} class="button"{/if}>{'Cancel sending of this campaign.'|i18n( 'extension/ezmailing/text' )}</button>
							</span>
							<p>{'Discard sending of this campaign, set to draft'|i18n( 'extension/ezmailing/text' )}</p>
							<div class="clear"></div>			
						</li>
						<li id="cancel_sending">
							<span {if or( and( $item.is_sending_in_progress_succeed, $item.is_cancelled|not(), $item.is_deleted|not() ), $item.is_sending_in_progress, $item.is_editable )} class="button-disabled"{/if}>
								<button type="submit" name="CancelButton" title="{'Cancel campaign.'|i18n( 'extension/ezmailing/text' )}"{if or($item.is_sending_in_progress_succeed,$item.is_sending_in_progress)} disabled="disabled" class="button-disabled"{else} class="button"{/if}>{'Cancel this campaign'|i18n( 'extension/ezmailing/text' )}</button>
							</span>
							<p>{'Cancel campaign.'|i18n( 'extension/ezmailing/text' )}</p>
							<div class="clear"></div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</form>

{undef $url}
{include uri="design:mailing/common/footer.tpl"}