{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{include uri="design:mailing/common/header.tpl" page='stats'}

<div id="ezmailing_container" class="statistics_container">
	<div id="ezmailing_content">
		<h2>{$item.subject}</h2>
		<div class="resume">
		{def $stats = fetch( 'mailing', 'stats', hash( 'mailing_id', $item.id ) )}
		    <div id="stat_description">
		    	<p id="number_of_opened_mails">
			    	<span>{cond( is_set( $stats.opened ), $stats.opened, 'NA' )}</span> {'mails opened'|i18n( 'extension/ezmailing/text' )}
		    	</p>		    
			    <p id="ctor">
			    	{'CTOR'|i18n( 'extension/ezmailing/text' )}: <span>{cond( and( is_set( $stats.opened ), is_set( $stats.clicked ) ),$stats.clicked|div( $stats.opened )|mul( 100 ),'NA')}</span>%
		    	</p>
		    </div>
	    	{if is_set( $stats.urls )}
	    	<div id="ezmailing_record_list">
	    		<h4>{'Urls clicked repartition'|i18n( 'extension/ezmailing/text' )}</h4>
	    		<ul>
	    		{foreach $stats.urls as $url => $nb}
			        <li class="ezmailing_list_item">
			            <div class="url">
			            	<h3>
			            		<a href="{$url}">{$url}</a>
			            	</h3>
			            </div>
			            <div class="click_number">
			            	<p>
			            		<span>{$nb}</span>{'Clics'|i18n( 'extension/ezmailing/text' )}
			            	</p>
			            </div>
			            <div class="click_persent">
			            	<p>
			            		<span>{$nb|div( $stats.clicked )|mul( 100 )|round }</span>%
			            	</p>
			            </div>
			            <div class="clear"></div>
			        </<li>
			        {/foreach}
	    		</ul>
	    	</div>
	    	{/if}		
		{undef $stats}
		</div>		
		
		<div class="tab-block ezmailing-controls-tabs" id="ezmailing-controls-tabs">
		    <ul class="tabs tabs-by-cookie">
		        <li class="first selected" id="node-tab-opened">
		        	<a href={concat("#","opened")|ezurl}>{'Open'|i18n( 'extension/ezmailing/text' )}</a>
		    	</li>
		        <li id="node-tab-repartition">
		        	<a href={concat("#","repartition")|ezurl}>{'Repartition'|i18n( 'extension/ezmailing/text' )}</a>
		    	</li>
		        <li id="node-tab-ontime-day">
		        	<a href={concat("#","ontime")|ezurl}>{'Per days'|i18n( 'extension/ezmailing/text' )}</a>
		    	</li>
		        <li id="node-tab-ontime-week">
		        	<a href={concat("#","ontime")|ezurl}>{'Per weeks'|i18n( 'extension/ezmailing/text' )}</a>
		    	</li>
		        <li id="node-tab-ontime-month">
		        	<a href={concat("#","ontime")|ezurl}>{'Per months'|i18n( 'extension/ezmailing/text' )}</a>
		    	</li>
		        <li id="node-tab-ontime-minute">
		        	<a href={concat("#","ontime")|ezurl}>{'Per minutes'|i18n( 'extension/ezmailing/text' )}</a>
		    	</li>
		        <li id="node-tab-ontime-hour">
		    		<a href={concat("#","ontime")|ezurl}>{'Per hours'|i18n( 'extension/ezmailing/text' )}</a>
				</li>
		        <li id="node-tab-os">
		        	<a href={concat("#","os")|ezurl}>{'OS'|i18n( 'extension/ezmailing/text' )}</a>
		    	</li>
		        <li id="node-tab-browser">
		        	<a href={concat("#","browser")|ezurl}>{'Browser'|i18n( 'extension/ezmailing/text' )}</a>
		    	</li>
		    </ul>
		    <div class="float-break"></div>
		    <div class="tabs-content">
		        <div class="tab-content selected" id="node-tab-opened-content">
		            <object width="800" height="400"  type="image/svg+xml" data={concat("mailing/graph/opened/",$item.id)|ezurl}>
		                <p>
		                	<img src={concat("mailing/graph/opened/",$item.id,"/png")|ezurl} />
		            	</p>
		            </object>
		        </div>
		        <div class="tab-content hide" id="node-tab-repartition-content">
		            <object width="800" height="400"  type="image/svg+xml" data={concat("mailing/graph/repartition/",$item.id)|ezurl}>
		                <p>
		                	<img src={concat("mailing/graph/repartition/",$item.id,"/png")|ezurl} />
		            	</p>
		            </object>
		        </div>
		        <div class="tab-content hide" id="node-tab-ontime-day-content">
		            <object width="800" height="400"  type="image/svg+xml" data={concat("mailing/graph/ontime/",$item.id,'/(unit)/day')|ezurl}>
		                <p>
		                	<img src={concat("mailing/graph/ontime/",$item.id,"/png",'/(unit)/day')|ezurl} />
		            	</p>
		            </object>
		        </div>
		        <div class="tab-content hide" id="node-tab-ontime-week-content">
		            <object width="800" height="400"  type="image/svg+xml" data={concat("mailing/graph/ontime/",$item.id,'/(unit)/week')|ezurl}>
		                <p>
		                	<img src={concat("mailing/graph/ontime/",$item.id,"/png",'/(unit)/week')|ezurl} />
		            	</p>
		            </object>
		        </div>
		        <div class="tab-content hide" id="node-tab-ontime-month-content">
		            <object width="800" height="400"  type="image/svg+xml" data={concat("mailing/graph/ontime/",$item.id,'/(unit)/month')|ezurl}>
		                <p>
		                	<img src={concat("mailing/graph/ontime/",$item.id,"/png",'/(unit)/month')|ezurl} />
		            	</p>
		            </object>
		        </div>
		        <div class="tab-content hide" id="node-tab-ontime-minute-content">
		            <object width="800" height="400"  type="image/svg+xml" data={concat("mailing/graph/ontime/",$item.id,'/(unit)/minute')|ezurl}>
		                <p>
		                	<img src={concat("mailing/graph/ontime/",$item.id,"/png",'/(unit)/minute')|ezurl} />
		            	</p>
		            </object>
		        </div>
		        <div class="tab-content hide" id="node-tab-ontime-hour-content">
		            <object width="800" height="400"  type="image/svg+xml" data={concat("mailing/graph/ontime/",$item.id,'/(unit)/hour')|ezurl}>
		                <p>
		                	<img src={concat("mailing/graph/ontime/",$item.id,"/png",'/(unit)/hour')|ezurl} />
		            	</p>
		            </object>
		        </div>
		        <div class="tab-content hide" id="node-tab-os-content">
		            <object width="800" height="400"  type="image/svg+xml" data={concat("mailing/graph/os/",$item.id)|ezurl}>
		                <p>
		                	<img src={concat("mailing/graph/os/",$item.id,"/png")|ezurl} />
		            	</p>
		            </object>
		        </div>
		        <div class="tab-content hide" id="node-tab-browser-content">
		            <object width="800" height="400"  type="image/svg+xml" data={concat("mailing/graph/browser/",$item.id)|ezurl}>
		                <p>
		                	<img src={concat("mailing/graph/browser/",$item.id,"/png")|ezurl} />
		            	</p>
		            </object>
		        </div>
		    </div>
		</div>
	</div>
</div>



{include uri="design:mailing/common/footer.tpl"}