{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{include uri="design:mailing/common/header.tpl" page='view'}

{def $url = $item.campaign_url}

<form method="post" action={concat( '/mailing/campaigns/edit/', $item.id )|ezurl}>
	<div id="ezmailing_container">
		<div id="ezmailing_content">
			<h2>{"Mailing Lists"|i18n('extension/ezmailing/text')}</h2>
			<div id="ezmailing_mailing_lists">
				<ul>
					{def $mainling_lists = $item.mailing_lists}
	                  {foreach $mainling_lists as $mailingList}
	                      <li>
	                            <div>
	                            	<p class="mailing_lists_lang">
	                            		<img src="{$mailingList.lang|flag_icon}" width="18" height="12" alt="{$mailingList.lang}" />&nbsp;
	                            		{$mailingList.lang}
                            		</p>
		                            <h3>{$mailingList.name|wash}</h3>
		                            <div class="clear"></div>                            
		                            <p class="mailing_list_registrations_count">
		                            	<span>{$mailingList.registrations_count}</span> {"registrations"|i18n('extension/ezmailing/text')}
	                            	</p>
	                            </div>
	                       </li>
	                   {/foreach}
	               {undef $mainling_lists} 
				</ul>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	<input type="hidden" value="{$item.id}" name="CampaignID" />
	<div id="ezmailing_actions_submit">
		<ul>
			<li id="edit_compain">
				<button type="submit" name="CampaignEditButton" title="{'Edit this campaign.'|i18n( 'extension/ezmailing/text' )}">{'Edit'|i18n( 'extension/ezmailing/text' )}</button>
			</li>
			<li id="send_compain">
				<button type="submit" name="CampaignSendButton" title="{'Send this campaign.'|i18n( 'extension/ezmailing/text' )}">{'Send'|i18n( 'extension/ezmailing/text' )}</button>
			</li>
			{if and( $item.is_draft_succeed, is_provided()|not() )}
			<li id="stat_compain">
				<button type="submit" name="CampaignStatsButton" title="{'Stats of this campaign.'|i18n( 'extension/ezmailing/text' )}">{'Stats'|i18n( 'extension/ezmailing/text' )}</button>
			</li>
		    {/if}
		    <li id="preview_compain">
				<a href="{$url}" target="_blank">{'Preview'|i18n( 'extension/ezmailing/text' )}</a>
			</li>
			<li id="export_compain">
				<button type="submit" name="CampaignHTMLExportButton" title="{'Export this campaign in HTML.'|i18n( 'extension/ezmailing/text' )}">{'HTML export'|i18n( 'extension/ezmailing/text' )}</button>
			</li>
		</ul>
		<div class="clear"></div>
	</div>
</form>

{undef $url}

{include uri="design:mailing/common/footer.tpl"}