{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{ezscript_require( array( 'ezjsc::jquery','ezjsc::jqueryio', 'register.js' ) )}
{include uri='design:mailing_registration/block_register.tpl'}