{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if is_set( $attribute_base )|not}
    {def $attribute_base = 'ContentObjectAttribute'}
{/if}
{ezcss_require(array('ezmailing_edit.css'))}
<div class="block ezmailingregistration">
    <div class="element">
    {def
        $lists = fetch('mailing','fetch',hash(
                                            'type','mailinglist',
                                            'sort_by', hash( 'name', 'asc')
                                        ))
        $registrations = $attribute.content
    }
        <ul>
        {foreach $lists as $mailing}
            <li><label><input
                    id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_mailingListID"
                    class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
                    name="{$attribute_base}_data_ezmailing_mailingListID_{$attribute.id}[]" value="{$mailing.id}"
                    {foreach $registrations as $registration}
                        {if and(
                            $registration.mailing_list|eq( $mailing ),
                            $registration.is_active)}
                                checked="checked"
                            {/if}
                    {/foreach}
                    type="checkbox"/>{$mailing.name|wash}</label></li>
        {/foreach}
        </ul>
    {undef $lists $registrations}
    </div>
    <div class="break"></div>
</div>
