{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if and( is_set( $edit ), $edit|eq( true() ) )}
	<div class="block">
    	<label>{$label|i18n( 'extension/ezmailing/text' )}{if $requires|contains( $identifier )}<span class="required">*</span>{/if}</label>
	    {def 
	       $base = ezini('eZJSCore', 'LocalScriptBasePath', 'ezjscore.ini')
	       $prefix = "mailing"
	       $suffix = "mailing"
	       $day = $item.$identifier|datetime( 'custom', '%d' )
	       $month = $item.$identifier|datetime( 'custom', '%m' )
	       $year = $item.$identifier|datetime( 'custom', '%Y' )
	       $second = $item.$identifier|datetime( 'custom', '%s' )
	       $minute = $item.$identifier|datetime( 'custom', '%i' )
	       $hour = $item.$identifier|datetime( 'custom', '%H' )
	    }
        {ezscript_require( 'ezjsc::yui2' )}
        {ezcss_require( concat( '/', $base.yui2, 'calendar/assets/calendar.css' ) )}
		<script type="text/javascript">
		(function() {ldelim}
		    YUILoader.addModule({ldelim}
		        name: 'datepicker',
		        type: 'js',
		        fullpath: '{"javascript/ezdatepicker.js"|ezdesign( "no" )}',
		        requires: ["calendar"],
		        after: ["calendar"],
		        skinnable: false
		    {rdelim});
		    YUILoader.require(["datepicker"]);
		    // Load the files using the insert() method.
		    var options = [];
		    YUILoader.insert(options, "js");
		{rdelim})();
		</script>
		<div class="blocElement">
			<div id="{$prefix}_datetime_cal_container_{$suffix}" style="display: none; position: absolute;"></div>
            <input id="{$prefix}_datetime_day" type="text" name="{$prefix}_datetime_day_{$suffix}" size="5" value="{$day}" />  
            <span class="date_separator">/</span>
            <input id="{$prefix}_datetime_month" type="text" name="{$prefix}_datetime_month_{$suffix}" size="5" value="{$month}" />
            <span class="date_separator">/</span>
            <input id="{$prefix}_datetime_year" type="text" name="{$prefix}_datetime_year_{$suffix}" size="5" value="{$year}" />
            <img class="datepicker-icon" src={"pictos/datepicker.png"|ezimage} id="{$prefix}_datetime_cal_{$suffix}" width="22" height="22" onclick="showDatePicker( '{$prefix}', '{$suffix}', 'datetime' );" />
            <div class="hidden">
            	<input id="{$prefix}_datetime_hour" type="text" name="{$prefix}_datetime_hour_{$suffix}" size="5" value="{$hour}" />
            	<input id="{$prefix}_datetime_minute" type="text" name="{$prefix}_datetime_minute_{$suffix}" size="5" value="{$minute}" />
            	<input id="{$prefix}_datetime_second" type="text" name="{$prefix}_datetime_second_{$suffix}" size="5" value="{$second}" />
            </div>
            <div class="clear"></div>
		</div>
		<div class="clear"></div>
		{undef $base $prefix $suffix $day $month $year $second $minute $hour}
    </div>
{else}
    {def 
       $day = $item.$identifier|datetime( 'custom', '%d' )
       $month = $item.$identifier|datetime( 'custom', '%m' )
       $year = $item.$identifier|datetime( 'custom', '%Y' )
    }
    <div class="block">
        <label>{$label|i18n( 'extension/ezmailing/text' )}:</label>
    	<p>{$day} / {$month} / {$year}</p>
        <div class="clear"></div>
    </div>
    {undef $day $month $year}
{/if}