{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if and( is_set( $edit ), $edit|eq( true() ) )}
	{def $attributeChildren = ezini( 'MailingUserAccountSettings', 'ChildrenAttributesFamilyStatus', 'ezmailing.ini' )}
	<div class="block">
		<label for="{$identifier}">{$label|i18n( 'extension/ezmailing/text' )}{if $requires|contains( $identifier )}<span class="required">*</span>{/if}</label>
		<select id="{$identifier}" name="{$identifier}" class="jqTransformField customCss customCss2">
			{foreach $attributeChildren as $status}
				<option value="{$status}">{$status|upfirst()|i18n( 'extension/ezmailing/text' )}</option>
			{/foreach}
		</select>
		<div class="clear"></div>
	</div>
{else}
    <div class="block">
        <label>{$label|i18n( 'extension/ezmailing/text' )}:</label>
        <p>{$item.$identifier|wash|upfirst()|i18n( 'extension/ezmailing/text' )}</p>
        <div class="clear"></div>
    </div>
{/if}