{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if and( is_set( $edit ), $edit|eq( true() ) )}
	{def $sexe = $item.$identifier}
	<div class="block">
        <label for="{$identifier}">{$label|i18n( 'extension/ezmailing/text' )}{if $requires|contains( $identifier )}<span class="required">*</span>{/if}</label>
       	<div class="radio_wrapper">
			<input id="male" type="radio" name="{$identifier}"{if $sexe|eq( 0 )} checked="checked"{/if} value="0" class="jqTransformField" />
			<label for="male">
				<img src={"pictos/male.png"|ezimage} alt="" width="24" height="29" />
			</label>
			<input id="female" type="radio" name="{$identifier}"{if $sexe|eq( 1 )} checked="checked"{/if} value="1" class="jqTransformField" />
			<label for="female" id="female_label">
				<img src={"pictos/female.png"|ezimage} alt="" width="24" height="29" />
			</label>		    				
		</div>
        <div class="clear"></div>
    </div>
    {undef $sexe}
{else}
    <div class="block">
        <label>{$label|i18n( 'extension/ezmailing/text' )}:</label>
        <p>{if $item.$identifier|eq( 0 )}{'Male'|i18n( 'extension/ezmailing/text' )}{else}{'Female'|i18n( 'extension/ezmailing/text' )}{/if}</p>
        <div class="clear"></div>
    </div>
{/if}