{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="box-header">
    <div class="box-tc">
        <div class="box-ml">
            <div class="box-mr">
                <div class="box-tl">
                    <div class="box-tr">
                        <h1 class="context-title">
                            <span>eZ Mailing <img src={"logo-novactive.png"|ezimage} width="78" /></span>
                            &nbsp;{$title}
                        </h1>
                        {* DESIGN: Mainline *}
                        <div class="header-mainline"></div>
                        {* DESIGN: Header END *}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>