{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="ezmailing_header" class="user_header">
	<form {if is_set($action)} action={$action|ezurl} {/if} method="post" name="campaignlistform{if is_set($blockid)}_{$blockid}{/if}">
        <h1>{$title}</h1>
        <button type="submit" name="CreateUserButton" title="{"Create new user"|i18n( 'extension/ezmailing/text' )}">{"Create new user"|i18n( 'extension/ezmailing/text' )}</button>
		<p id="ezmailing_header_text">
        {"List of users with their registration."|i18n( 'extension/ezmailing/text' )}{"Use filters to refine your search."|i18n( 'extension/ezmailing/text' )}
        </p>
	</form>
	<div class="clear"></div>
</div>