{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id="ezmailing_header" class="user_header view">
    <h1>{$title}</h1>
    <p id="ezmailing_header_text">
        {"Display user information."|i18n( 'extension/ezmailing/text' )}
    </p>
    <div id="ezmailing_header_details">
        <div id="left_details">
            <p>
                <strong>{"ID"|i18n('extension/ezmailing/text')}</strong> : {$item.id}
            </p>
            <p>
                <strong>{"Origin"|i18n('extension/ezmailing/text')}</strong> : {$item.origin}
            </p>
        </div>
        <div id="right_details">
            <p>
                <strong>{"Registred"|i18n( 'extension/ezmailing/text' )}</strong> : {$item.registred|l10n( 'shortdatetime' )}
            </p>
            <p>
                <strong>{"Updated"|i18n( 'extension/ezmailing/text' )}</strong> : {$item.updated|l10n( 'shortdatetime' )}
            </p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <div id="grabber">
        <a href="#" title="{"AFFICHER/CACHER DETAILS"|i18n( 'extension/ezmailing/text' )}">
            <img src={"pictos/grabber.png"|ezimage()} width="38" height="15" />
        </a>
    </div>
    <div class="clear"></div>
</div>