{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<html xmlns="http://www.w3.org/1999/html">
<head>
</head>
<body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">

<div style="font-family:Verdana, Geneva, sans-serif; font-size:12px; color:#434343;background:#f6f6f6; padding:10px">

#EZMAIL_CONTENT#


</div>

</body>
</html>